---
title: "R Notebook"
output: html_notebook
editor_options:
  chunk_output_type: console
bibliography: /Users/christophercrawford/Google Drive/Library/library.bib
---
R notebook for loading and processing the land cover time-series raster data from @Yin2020.


```{r initialize}
source("scripts/0_start.R")

# define color palette for plotting:
# 1. Non-veg
# 2. Woody veg
# 3. Crop
# 4. Grassland
plot_cols <- c("gray80", # gray, 1. Non-veg
               terrain.colors(9)[1], # dark green, 2. Woody veg
               terrain.colors(9)[5], # gold, 3. Crop
               terrain.colors(9)[3] # light green, 4. Grassland
               )
plot_cols_new <- c("gray80", # gray, 1. Non-veg
               terrain.colors(9)[5], # gold, 2 (formerly 3) Crop
               terrain.colors(9)[3], # light green, 3 (formerly 4) Grassland
               terrain.colors(9)[1]  # dark green, 4 (formerly 2) Woody veg
               )

plot_breaks <- c(0, 1, 2, 3, 4)

# show_col(terrain.colors(20))
# show_col(topo.colors(20))
# show_col(cm.colors(20))
# 
# show_col(plot_cols)
# show_col(plot_cols[c(1, 3, 2)])
```

```{r load-data}
# Land use class codes:
#       1. Non-vegetated area (e.g. water, urban, barren land)
#       2. Woody vegetation
#       3. Cropland 
#       4. Herbaceous land (e.g. grassland)

bs <- brick(paste0(p_dat, "Abandonment/belarus_small.tif"))
bs_dt <- as.data.table.raster(bs)


# GEE
b_files <- list.files(paste0(p_dat, "Abandonment/belarus_tiles/"))

# just belarus files, but not necessary
# b_files <- list.files(paste0(p_dat, "Abandonment/belarus_tiles/")) %>%
#   grep("belarus", ., value = TRUE)

b1 <- brick(paste0(p_dat, "Abandonment/belarus_tiles/", b_files[1]))
s <- brick(paste0(p_dat_derived, "input_rasters/shaanxi.tif"))

s
plot(s[[1]])
ncell(b1)
ncell(s)
res(s)
res(b1)
nlayers(b1)
nlayers(s)
raster::area(s[[1]])
22592862 * res(s)[1] * res(s)[2]
34668544 * res(b1)[1] * res(b1)[2]


res(b1)[1] * 110 * 1000 # about 30 m checks out
res(s)[1] * 110 * 1000 # about 30 m checks out
b_tiles

plot(s[[1]], main = "Shaanxi 1987", breaks = c(0, plot_cols$breaks), col = plot_cols$color)

b_tiles <- lapply(1:6, function(i) {
    brick(paste0(p_dat, "Abandonment/belarus_tiles/", b_files[i]))})
names(b_tiles) <- b_files

names(b_tiles[[6]])

# Shaanxi is much much smaller than Belarus
ncell(s) # 94.4 M
ncell(b87_r) # 22.59 M
# they have the same resolution
res(s)
res(b_tiles)




# as data.tables
dt <- as.data.table.raster(s)
object_size(dt)
dt <- dt_s
names(dt) <- gsub("andcover", "y", names(dt))
ncol(dt)
dt[, .N, by = .(y1987)] # one year


fwrite(dt, file = paste0(p_dat_derived, "shaanxi.csv"))
dt <- fread(input = paste0(p_dat_derived, "shaanxi.csv"))
```

```{r load-data-derived}


b_age <- fread(input = paste0(p_dat_derived, "belarus_age.csv"))
s_age <- fread(input = paste0(p_dat_derived, "shaanxi_age.csv"))


b_length <- fread(input = paste0(p_dat_derived, "belarus_length.csv"))
s_length <- fread(input = paste0(p_dat_derived, "shaanxi_length.csv"))


b_max_length <- fread(input = paste0(p_dat_derived, "belarus_max_length.csv"))
s_max_length <- fread(input = paste0(p_dat_derived, "shaanxi_max_length.csv"))

# rasters
s_age_r <- brick(paste0(p_dat_derived, "shaanxi_age.tif"))
b_age_r <- brick(paste0(p_dat_derived, "belarus_age.tif"))



```

```{r load-all-sites}
# Primary sites
# 1. Shaanxi - He
# 2. Belarus (Smolensk) - He
# 3. Chongqing - Yanhua (not great -fields are small, mountainous, and lots of clouds) - look at the data to see. 
# 4. Goias - Ben
# 5. Mato Grasso - Amintas
# 6. Nebraska - Seth
# 7. Wisconsin - David
# 
# ok
# 8. Volgograd - Natalia
# 9. Orenburg - Natalia
# 10. Bosnia & Herzegovina (medium)
# 11. Iraq (medium good, low accuracy over years, but good single accuracy)
# 
# exclude 
# 12. Nepal - Johanna
# 13. Sardinia - Kasia
# 14. Uganda - Niwaeli

# CAREFUL!!!!! Land Cover codes are different for each file:
# Land use class codes: (for He's site, Shaanxi and Belarus)
#       1. Non-vegetated area (e.g. water, urban, barren land)
#       2. Woody vegetation
#       3. Cropland 
#       4. Herbaceous land (e.g. grassland)
# 
# Also be careful of years: Nebraska runs from 1986-2018, while all other sites run 1987-2017.

# Shaanxi (China):  1 others;     2 forest,     3 cropland;     4 grassland
# Belarus - Russia: 1 others;     2 forest,     3 cropland;     4 grassland
# Brazil Goias:     1 others;     2 forest,     3 cropland;     4 grassland
# Brazil Amazon:    1 others;     2 forest;     3 cropland;     4 grassland
# Bosnia:           1 others;     2 forest;     3 cropland;     4 grassland
# Chongqing:        1 others;     2 forest;     3 cropland;     4 grassland

# Iraq:             1 others;     2 cropland;   3 forest;       4 grassland
# Nebraska:         1 cropland;   2 forest;     3 others;       4 grassland
# Russia Orenburg:  1 others;     2 cropland;   3 grassland;    4 forest
# Russia Volgograd: 1 others;     2 cropland;   3 grassland;    4 forest
# Wisconsin:        1 cropland;   2 grassland;  3 forest;       4 others

# list of all sites
site_list <- sort(
  c("shaanxi", "belarus", 
    "chongqing", "goias", "mato_grosso",
    "nebraska", "wisconsin", "volgograd",
    "orenburg", "bosnia_herzegovina", "iraq") 
  )

site_label_list <- sort(
  c("_s", "_b", 
    "_c", "_g", "_mg", 
    "_n", "_w", "_v", 
    "_o", "_bh", "_i")
  )

site_merge_layers <- site_list[c(3, 4, 5, 7, 8, 10)]
c("chongqing", "goias", "iraq", "nebraska", "orenburg", "volgograd")

site_update_lc <- site_list[c(5, 7, 8, 10, 11)]
c("iraq", "nebraska", "orenburg", "volgograd", "wisconsin")


# make a data.frame outlining site names, labels, whether to update land cover, whether to merge, original land cover codes etc. 
site_df <- data.frame(site = site_list,
                      label = site_label_list) %>% 
  mutate(merge_layers = ifelse(site %in% site_merge_layers, "Yes", "No"),
         update_lc = ifelse(site %in% site_update_lc, "Yes", "No"),
         other = 1, 
         woody_veg = 2,
         cropland = 3,
         grassland = 4
         )

# Update the following:
# Iraq:             1 others;     2 cropland;   3 forest;       4 grassland
# Nebraska:         1 cropland;   2 forest;     3 others;       4 grassland
# Russia Orenburg:  1 others;     2 cropland;   3 grassland;    4 forest
# Russia Volgograd: 1 others;     2 cropland;   3 grassland;    4 forest
# Wisconsin:        1 cropland;   2 grassland;  3 forest;       4 others

site_df[site_df$site == "iraq", 
        c("other", "cropland", "woody_veg", "grassland")] <- 1:4

site_df[site_df$site == "nebraska", 
        c("cropland", "woody_veg", "other", "grassland")] <- 1:4

site_df[site_df$site == "orenburg", 
        c("other", "cropland", "grassland", "woody_veg")] <- 1:4

site_df[site_df$site == "volgograd", 
        c("other", "cropland", "grassland", "woody_veg")] <- 1:4

site_df[site_df$site == "wisconsin", 
        c("cropland", "grassland", "woody_veg", "other")] <- 1:4

site_df

# save site_df
write_csv(site_df, path = paste0(p_dat_derived, "site_df.csv"))






# ---------------------------------------------------
# load final tifs 
# ---------------------------------------------------

# year of first abandonment maps
yoa_files <- list.files(paste0(p_dat, "Abandonment/year_of_abandonment/"))
map_files <- list.files(paste0(p_dat, "Abandonment/final_maps/"))

r
r <- vector(mode = "list", length = length(map_files)# + 2
            )
r[[1]] <- brick(paste0(p_dat, "Abandonment/shaanxi.tif"))
r[[2]] <- brick(paste0(p_dat_derived, "input_rasters/belarus.tif")) # merged version


r <- lapply(seq_along(map_files), function(i) {
  brick(paste0(p_dat, "Abandonment/Final_maps/", map_files[i]))
  }
  )

names(r) <- map_files #site_list


plot(c(ncell(b), ncell(s), sapply(seq_along(r), FUN = function(i) ncell(r[[i]]))))

test <- brick(paste0("/Users/christophercrawford/Google Drive/_Projects/data/Abandonment/Final_maps/", map_files[2]))
test
cellStats(test, "mean")
cellStats(test, )
freq(test)


b
plot(b[[1]])

plot(test)
ncell(test)
# GEE

# just belarus files, but not necessary
# b_files <- list.files(paste0(p_dat, "Abandonment/belarus_tiles/")) %>%
#   grep("belarus", ., value = TRUE)

b1 <- brick(paste0(p_dat, "Abandonment/belarus_tiles/", b_files[1]))
s <- brick(paste0(p_dat_derived, "input_rasters/shaanxi.tif"))
s

plot(s[[1]], main = "Shaanxi 1987", breaks = c(0, plot_cols$breaks), col = plot_cols$color)

b_tiles <- lapply(1:6, function(i) {
    brick(paste0(p_dat, "Abandonment/belarus_tiles/", b_files[i]))})
names(b_tiles) <- b_files


# useful, but not necessary:

# filling things in conditionally, using dplyr or just base R
site_df[site_df$update_lc == "No", c("other", "woody_veg", "cropland", "grassland")] <- 1:4

site_df <- site_df %>% 
  mutate(other = ifelse(update_lc == "No" , 1, other),
         woody_veg = ifelse(update_lc == "No" , 2, woody_veg),
         cropland = ifelse(update_lc == "No" , 3, cropland),
         grassland = ifelse(update_lc == "No" , 4, grassland)
         )

```

```{r combine-years-brick}
# 1. if necessary combine individual years into a single brick (Chongqing, Goias, Iraq, Nebraska, Orenburg, and Volgograd)
# 2. write out the combined file back to the original folder, if it didn't exist already
# 3. update the land cover codes for those sites that follow different conventions, so that all match the following:
# Land use class codes: (for He's site, Shaanxi and Belarus)
#       1. Non-vegetated area (e.g. water, urban, barren land)
#       2. Woody vegetation
#       3. Cropland 
#       4. Herbaceous land (e.g. grassland)


# 4. write out final input raster to paste0(p_dat_derived, "input_rasters/"), to the 

# sites
site_df

# set site
site <- site_merge_layers[2]
site <- "wisconsin"
i

folder_paths <- list.dirs(path = paste0(p_dat, "Abandonment/final_maps_raw"), 
                       full.names = TRUE, recursive = FALSE)
  
folder_names <- sapply(seq_along(folder_paths), FUN = function(i) {
  folders_l <- unlist(strsplit(folder_paths[[i]], "[/]"))
  folders_l <- folders_l[length(folders_l)]
  }
  )

merge_files <- lapply(site_merge_layers, FUN = function(i) {
      list.files(paste0(p_dat, "Abandonment/final_maps_raw/", i), full.names = TRUE)
    })

names(merge_files) <- site_merge_layers
for (i in 1:6) {
  print(paste0(length(merge_files[[i]]), ": ", names(merge_files[i])))
  }

site_df[site_df$merge_layers == "Yes", "site"]



964/60 # 16 minutes. Better upload the data and go from there. 
cc_merge_rasters(site = "wisconsin", site_df = site_df)




gsub("X5_Volg_172_026_landcover", "y", names(v))

l <- lapply(merge_files, function(i) raster(i))

merge_files[[1]][1]
length(merge_files)
```


```{r explore-test-merged-rasters}

rasters <- lapply(site_list, function(site) {
  brick(paste0(p_dat_derived, "input_rasters/", site, ".tif"))
  }
  )
names(rasters) <- site_list

test <- read.csv(paste0(p_dat, "Abandonment/final_maps_raw/", site, ".csv"))
unlist(test, use.names = F) == names(raster_stack)


# test that the recoding worked
freq(raster_stack[[1]])

```



```{r simple-plots}
show_col(plot_cols) # (topleft = 1, topright = 2, bottomleft = 3, bottomright = 4)
# gray,         1. Non-veg
# dark green,   2. Woody veg
# gold,         3. Crop
# light green,  4. Grassland

plot(b87_r, main = "Belarus 1987", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

plot(bs$smolensk1987, add = T, legend = F, col = "blue")
plot(bt$smolensk1987, add = T, legend = F, col = "red")
bs

plot(bs$smolensk1987, main = "Subset: Belarus 1987", 
     breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

plot(bt$smolensk1987, main = "Subset Subset: Belarus 1987", 
     breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

# --------------
# animate
# --------------
# https://www.rdocumentation.org/packages/raster/versions/3.1-5/topics/animate

animate(bt, pause = 0.5, zlim = c(1, 4), maxpixels=5000, n=1,
        breaks = c(0, plot_cols$breaks), col = plot_cols$color)

```


```{r final-processing-workflow-w-tictoc}
# script for computing cluster

library(raster)
library(data.table)
library(devtools)
library(tictoc)

# devtools::install_github("ldemaz/dtraster")
library(dtraster)

tic("Full script")

file <- "/Users/christophercrawford/Google Drive/_Projects/data/Abandonment/belarus_small.tif"
name <- "shaanxi"
path <- p_dat_derived

# load custom filtering functions
source("scripts/util/_util_dt_filter_functions.R")


tic("load raster")
r <- brick(file)

nlayers(r) # 31 years in the time series
names(r) <- paste0("y", 1:nlayers(r))
toc()



# load as a data.table
tic("load data.table")
dt <- as.data.table.raster(r)
toc()

# update names of data.table, if not already updated
names(dt) <- gsub("andcover", "y", names(dt))

# write out data.table as a csv
fwrite(dt, file = paste0(path, name, ".csv"))


# ----------------------
# start heavy processing

tic("update land cover classes")
cc_update_lc(dt, crop_code = 0, noncrop_code = 1)
toc()

tic ("remove NAs")
dt <- na.omit(dt)
toc()

tic("filter non abandonment pixels")
dt <- cc_remove_non_abn(dt)
toc()


tic("calculate age")
cc_calc_age(dt)
toc()


tic("erase non abandonment periods")
cc_erase_non_abn_periods(dt)
toc()


tic("write out cleaned abandonment age data.table")
fwrite(dt, file = paste0(path, name, "_age.csv"))
toc()
path

tic("make diff")
dt_diff <- cc_diff_dt(dt)
toc()

# write out dt_diff
tic("write out dt_diff")
fwrite(dt_diff, file = paste0(path, name, "_diff.csv"))
toc()


tic("extract length")
length <- cc_extract_length(dt_diff)
toc()


# write out length
length <- data.table(length = length)
fwrite(length, file = paste0(path, name, "_length.csv"))

# write out 

# explore some stats:
length[, .N, by = length]
length[, mean(length)] # mean time abandoned if using no threshold
length[length >= 5, mean(length)] # mean time abandoned, if using 3 year abandonment definition threshold


# final toc()
toc()
```

```{r shaanxi-processing}
# script for computing cluster

library(raster)
library(data.table)
library(devtools)
library(tictoc)

# devtools::install_github("ldemaz/dtraster")
library(dtraster)
path_in <- "/Users/christophercrawford/Google Drive/_Projects/data/Abandonment/eefull/"
path_out <- p_dat_derived

# shaanxi run
name <- "shaanxi"
file <- paste0(path_in, name, ".tif")

# load custom filtering functions
source("scripts/util/_util_dt_filter_functions.R")

# load raster
r <- brick(file)

nlayers(r) # 31 years in the time series
names(r) <- gsub("andcover", "y", names(r))
# names(r) <- paste0("y", 1986 + 1:nlayers(r))


# load as a data.table
dt <- as.data.table.raster(r)

# write out data.table as a csv
fwrite(dt, file = paste0(path_out, name, ".csv"))


# # read in data.table directly
# dt <- fread(file = paste0(path_out, name, ".csv"))
# nrow(dt) # pre processing 22,592,862
# nrow(dt) # 8,290,074 # post processing
# 
# # update names of data.table, if not already updated
# names(dt) <- gsub("andcover", "y", names(dt))


# ----------------------
# start heavy processing 

tic()
# update land cover classes
cc_update_lc(dt, crop_code = 0, noncrop_code = 1)

# remove NAs
dt <- na.omit(dt)

# filter non abandonment pixels
dt <- cc_remove_non_abn(dt)

# calculate age
cc_calc_age(dt)

# erase non abandonment periods
cc_erase_non_abn_periods(dt)

# write out cleaned abandonment age data.table
fwrite(dt, file = paste0(path_out, name, "_age.csv"))

# make diff
dt_diff <- cc_diff_dt(dt)

# write out dt_diff
fwrite(dt_diff, file = paste0(path_out, name, "_diff.csv"))

# extract length
length <- cc_extract_length(dt_diff)

# write out length
length <- data.table(length = length)
fwrite(length, file = paste0(path_out, name, "_length.csv"))



# explore some stats:
length[, .N, by = length]
length[, mean(length)] # mean time abandoned if using no threshold
length[length >= 5, mean(length)] # mean time abandoned, if using 3 year abandonment definition threshold

toc()
```

```{r save-age-rasters}

# as a function

age_r <- cc_save_age_rasters(name = "shaanxi")
names(age_r) <- paste0("y", 1987:2017)
plot(age_r$y2017, main = "Age of abandonment in 2017")

age_r <- brick("/Users/christophercrawford/Google Drive/_Projects/abandonment_trajectories/data_derived/shaanxi_age_1.tif")
identical(age_r, age_r1)

cellStats(age_r[[31]] - age_r1[[31]], "sum")


# works fine for shaanxi, but running into issues with belarus... see below


# -------------
# development

dt <- fread(file = paste0(path_out, name, "_age.csv"))

s2017 <- dt[, .(x, y, y2017)]

# convert age dt to raster
age_r <- dt_to_raster(dt, crs(s))


plot(age_r$y2017, main = "Age of Abandonment, 2017")
rasterVis::levelplot(age_r$y2017)
# animate
names(age_r)
animate(age_r, pause = 0.3, main = paste0("Abandonment Age, ", 1987:2017), maxpixels = 500000, n = 1)

names(age_r)
# write raster
writeRaster(age_r, filename = paste0(p_dat_derived, name, "_age.tif"))
names(age_r)

# reload, and rename
age_r <- brick(paste0(p_dat_derived, name, "_age.tif"))
names(age_r) <- paste0("y", 1987:2017)

# just 2017
age_2017_r <- dt_to_raster(dt[, .(x, y, y2017)], crs(s), filename = paste0(p_dat_derived, name, "_age_2017.tif"))


plot(age_r$y2017, main = "Age of abandonment in 2017")


# final code
r <- dt_to_raster(dt, crs("+proj=longlat +datum=WGS84 +no_defs"))
writeRaster(r, filename = paste0(directory, name, "_age.tif"))
brick(paste0(directory, name, "_age.tif"))
```

```{r merging-belarus-chunks}
# -------------------------------
# merge original belarus rasters

b <- merge(b_tiles[[1]], 
                 b_tiles[[2]],
                 b_tiles[[3]],
                 b_tiles[[4]],
                 b_tiles[[5]],
                 b_tiles[[6]])
names(b) <- paste0("y", 1987:2017)
tic()
writeRaster(b, filename = paste0(p_dat_derived, "belarus.tif"))
toc()

plot(b$y1987, col = plot_cols$color, breaks = c(0, plot_cols$breaks), main = "merged")
plot(b87_r, col = plot_cols$color, breaks = c(0, plot_cols$breaks), main = "1987 direct")
plot(b87_r - b$y1987)

cellStats(b$y1987 - b87_r, "sum")



# -------------------------------
# save Belarus 1 as a raster:
# b1_age_r <- cc_save_age_rasters(name = "belarus1")  

# manually
b1_age_r1 <- dt_to_raster(b1_age[1:2000000], crs("+proj=longlat +datum=WGS84 +no_defs"))
b1_age_r2 <- dt_to_raster(b1_age[2000001:4000000], crs("+proj=longlat +datum=WGS84 +no_defs"))

plot(b1_age_r1$y2017)
plot(b1_age_r2$y2017, add = T)

# -------------------------------
# test merging belarus chunks
merge_test <- merge(b1_age_r1, b1_age_r2)
merge_test
ncell(merge_test)
ncell(b1_age_r1) + ncell(b1_age_r2)
plot(merge_test$layer.31)
plot(extent(b1_age_r1), add = T, col = "black")
plot(extent(b1_age_r2), add = T, col = "black")
b1_age_r3 <- dt_to_raster(b1_age[1:4000000], crs("+proj=longlat +datum=WGS84 +no_defs"))
cellStats(merge_test - b1_age_r3, "sum") # these are the same, and it looked like it worked just fine, subtracting sequentially.


# try merging a full brick
b11 <- dt_to_raster(b1_age[1:100000][order(x),], crs("+proj=longlat +datum=WGS84 +no_defs"))
b12 <- dt_to_raster(b1_age[100001:200000][order(x),], crs("+proj=longlat +datum=WGS84 +no_defs"))
plot(b12$y2017)
test <- dt_to_raster(b1_age[1:200][order(x),], crs("+proj=longlat +datum=WGS84 +no_defs"))

writeRaster(b1_age_r, filename = paste0(directory, "belarus1", "_age.tif"))
plot(b1_age_r$y2017)

# reload, and assign names
b1_age_r <- brick(paste0(directory, "belarus1", "_age.tif"))
names(b1_age_r) <- paste0("y", 1987:2017)

plot(b1_age_r$y2017, main = "Age of abandonment in 2017")

```

```{r belarus-processing}

# belarus runs, for loop
run <- 1 # change this for each belarus run

# initial test
tic()
cc_process_rasters(input_raster_file = paste0(p_dat, "Abandonment/belarus_tiles/", b_files[1]),
                     name = paste0("belarus", 1), 
                     path_out = p_dat_derived,
                     gsub_pattern = "smolensk")
toc()

tic()
for(run in 1:6) {
  cc_process_rasters(input_raster_file = paste0(p_dat, "Abandonment/belarus_tiles/", b_files[run]),
                     name = paste0("belarus", run), 
                     path_out = p_dat_derived,
                     gsub_pattern = "smolensk")
}
toc()




# -------------------------------
# load and check the belarus data
b1_dt <- fread(input = paste0(p_dat_derived, "belarus1.csv"))
b1_diff <- fread(input = paste0(p_dat_derived, "belarus1_diff.csv"))

b1_age <- fread(input = paste0(p_dat_derived, "belarus1_age.csv"))
b2_age <- fread(input = paste0(p_dat_derived, "belarus2_age.csv"))
b3_age <- fread(input = paste0(p_dat_derived, "belarus3_age.csv"))
b4_age <- fread(input = paste0(p_dat_derived, "belarus4_age.csv"))
b5_age <- fread(input = paste0(p_dat_derived, "belarus5_age.csv"))
b6_age <- fread(input = paste0(p_dat_derived, "belarus6_age.csv"))


# save rasters:
cc_save_age_rasters(name = "belarus1") # not enough memory

dt <- fread(file = paste0(p_dat_derived, "belarus1_age.csv"))
shaanxi_age <- fread(file = paste0(p_dat_derived, "shaanxi_age.csv"))
nrow(dt)
nrow(shaanxi_age)
r <- dt_to_raster(dt, crs("+proj=longlat +datum=WGS84 +no_defs"))
writeRaster(r, filename = paste0(p_dat_derived, "belarus1_age.tif"))

env_size(ls())
plot(r)

# ------------------------------
# merge and save 2017 age layer as a raster
# test merge
b_age_2017 <- rbindlist(list(b1_age[, .(x, y, y2017)],
                            b2_age[, .(x, y, y2017)],
                            b3_age[, .(x, y, y2017)],
                            b4_age[, .(x, y, y2017)],
                            b5_age[, .(x, y, y2017)],
                            b6_age[, .(x, y, y2017)])
                       )

fwrite(b_age_2017, file = paste0(p_dat_derived, "belarus_age_2017.csv"))

b_age_2017_r <- dt_to_raster(b_age2017, crs("+proj=longlat +datum=WGS84 +no_defs"))
plot(b_age_2017_r, main = "Belarus, 2017 - age of abandoned croplands")
plot(extent(b_tiles[[1]]), add = T, col = "black")
plot(extent(b_tiles[[2]]), add = T, col = "black")
plot(extent(b_tiles[[3]]), add = T, col = "black")
plot(extent(b_tiles[[4]]), add = T, col = "black")
plot(extent(b_tiles[[5]]), add = T, col = "black")
plot(extent(b_tiles[[6]]), add = T, col = "black")

extent(b_tiles[[1]])

writeRaster(b_age2017_r, filename = paste0(p_dat_derived, "belarus_age_2017.tif"))
b_age2017_r <- raster(paste0(p_dat_derived, "belarus_age_2017.tif"))



b1_length <- fread(input = paste0(p_dat_derived, "belarus1_length.csv"))

b_length


env_size(ls())

# ------------------------------- #
# ultimately I processed the merged Belarus raster file in one go on adroit, using the script: 
# /Users/christophercrawford/Google Drive/_Projects/abandonment_trajectories/scripts/cluster/process_calc_age_belarus.R
# ------------------------------- #


```

```{r inspect-adroit-belarus}
# check cluster output to make sure it worked correctly

# merge individual lengths

b1_length <- fread(input = paste0(p_dat_derived, "belarus1_length.csv"))
b2_length <- fread(input = paste0(p_dat_derived, "belarus2_length.csv"))
b3_length <- fread(input = paste0(p_dat_derived, "belarus3_length.csv"))
b4_length <- fread(input = paste0(p_dat_derived, "belarus4_length.csv"))
b5_length <- fread(input = paste0(p_dat_derived, "belarus5_length.csv"))
b6_length <- fread(input = paste0(p_dat_derived, "belarus6_length.csv"))

b_length_merge <- rbindlist(list(b1_length,
                                 b2_length,
                                 b3_length,
                                 b4_length,
                                 b5_length,
                                 b6_length))

# load the full belarus length file
b_length <- fread(input = paste0(p_dat_derived, "belarus_length.csv"))
# the order is off, because of the way the length extraction code works, extracting each year's column individually, and rbinding those.


# check to see if they're identical
identical(b_length[order(length)], b_length_merge[order(length)])


# initial stats on length, Belarus


# explore some stats:
s_length <- fread(input = paste0(p_dat_derived, "shaanxi_length.csv"))
s_length
b_length
s_length[, .N, by = length]
b_length[, .N, by = length]

object_size(b_length)
s_length[, site := "shaanxi"]
b_length[, site := "belarus"]

length_all <- rbindlist(list(s_length, b_length))
object_size(length_all)

dat <- length_all[, .(mean_length = mean(length)), by = site]
dat2 <- length_all[length >= 5, .(mean_length_thr5 = mean(length)), by = site]
dat <- merge(dat, dat2, by = "site", sort = FALSE)
dat

# max length
```

```{r histograms}
# plot histograms
# beware... because of the way the bins are determined, the default histogram automatically lumps 1 and 2 together. better to first distill the data and use ggplot 
hist(s_length[[1]], main = "Histogram of Length of Time Abandoned \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")

hist(b_length[[1]])

hist(length_all[site == "shaanxi", length], main = "Histogram of Abandonment Period Lengths \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")

hist(length_all[site == "belarus", length], main = "Histogram of Abandonment Period Lengths \n Belarus/Russia", xlab = "Time (years)")

hist(b_length[[1]], main = "Histogram of Abandonment Period Lengths \n Belarus/Russia", xlab = "Time (years)")
toc()

hist(b_length[[1]], main = "right = TRUE")
hist(b_length[[1]], right = FALSE, main = "right = FALSE")


# to use with ggplot, first distill the data

b_distill <- b_length[, .(freq = .N), by = length]
b_distill[, site := "belarus"]
s_distill <- s_length[, .(freq = .N), by = length]
s_distill[, site := "shaanxi"]

distill <- rbind(b_distill, s_distill)

b_max_distill <- b_max_length[, .(freq = .N), by = max_length]
b_max_distill[, site := "belarus"]
s_max_distill <- s_max_length[, .(freq = .N), by = max_length]
s_max_distill[, site := "shaanxi"]
max_distill <- rbind(b_max_distill, s_max_distill)

# ggplots
# both site histograms
dat

length_plot <- ggplot(data = distill) + 
  labs(title = "Histogram of all periods of abandonment") +
  geom_col(mapping = aes(x = length, y = freq), fill = "gray50") +
  facet_grid(rows = vars(site), scales = "free") +
  geom_vline(xintercept=5, linetype="dashed", 
             color = "red", size = 0.75) +
  geom_vline(xintercept=20, linetype="dashed", color = "dark green", size = 0.75) +
  theme_classic()

# max_length
max_length_plot <- ggplot(data = max_distill) + 
  labs(title = "Histogram of max abandonment length per pixel") +
  geom_col(mapping = aes(x = max_length, y = freq), fill = "gray50") +
  facet_grid(rows = vars(site), scales = "free") +
  geom_vline(xintercept=5, linetype="dashed", 
             color = "red", size = 0.75) +
  geom_vline(xintercept=20, linetype="dashed", color = "dark green", size = 0.75) +
  theme_classic()


length_plot
max_length_plot
dat




# just belarus
ggplot(data = b_distill) + 
  geom_col(mapping = aes(x = length, y = freq), fill = "black") +
  theme_classic()

ggplot(data = b_length, aes(length)) + 
  geom_histogram() +
  theme_classic() # took forever!! Beware...
```


```{r calc-max-age}
# calculate the maximum length of time abandoned for each pixel:
# not sure this code works yet... try with a smaller dt first. 
dt <- b1_age[1:100000]
dt
tic()
dt[, max_length := max(.SD), .SDcols = -c("x", "y"), by = .(x, y)]
toc() # 14.56 sec
getDTthreads() # ? no speed up ?

# testing function: it works!
dt1 <- b1_age[1:100000]
cc_calc_max_age(dt1, name = "belarus1")
identical(dt[, .(x,y,max_length)], dt1)
dt1 <- fread(input = paste0(p_dat_derived, "belarus1_max_length.csv"))

286.417 * nrow(b1_age)/nrow(dt) / 60 # 41 minutes, 40 minutes for the full dataset

max1 <- dt_to_raster(dt[, .(x, y, max_length)], crs("+proj=longlat +datum=WGS84 +no_defs"))

# one can also directly calculate this using raster::calc(), which ends up being faster.
tic()
max <- calc(b1_age_r1, fun = function(r){max(r, na.rm = TRUE)})
toc()
plot(max) # 130.958 sec
warnings()

cellStats(max1 - max, "sum")
plot(max1)
plot(max)
```


```{r parallel-dt}


```



```{r animation}
name <- "shaanxi"
age_r <- brick(paste0(p_dat_derived, name, "_age.tif"))
names(age_r) <- paste0("y", 1987:2017)
# plot(age_r$y2017)

# first, with animate package
saveGIF(animate(age_r, 
                main = paste0(
                  "Abandonment Age, ", 
                  capwords(name), " ", 
                  1987:2017), 
                maxpixels = 500000, 
                n = 1), 
        movie.name = paste0(
          p_dat_derived, name, "_age_animation.gif")
        )

# now, with magick
age_r_gif <- image_read(paste0(p_dat_derived, name, "_age_animation.gif"))
age_r_gif <- image_animate(age_r_gif)
image_write(shaanxi_age_gif, paste0(p_dat_derived, name, "_age_animation.gif"))


# make it into a function:

# take an animation made with raster::animate(), and save it as a GIF with animation::saveGIF()
cc_save_gif <- function(raster, 
                        titles = names(raster), 
                        file_out, 
                        npixels = 5000,
                        frames_per_second = 5) {
  
  # use animation::saveGIF() to save raster::animate()
  saveGIF(animate(raster, main = titles, maxpixels = npixels, n = 1), 
          movie.name = file_out)
  
  gif <- image_animate(image_read(file_out), fps = frames_per_second)
  image_write(gif, file_out)
}


# run the function:

# name <- "shaanxi"
name <- "belarus"
age_r <- brick(paste0(p_dat_derived, name, "_age.tif"))
names(age_r) <- paste0("y", 1987:2017)
plot(age_r$y2017)

tic()
cc_save_gif(raster = age_r, 
            npixels = 500000, 
            titles = paste0("Abandonment Age, ", 
                            capwords(name), " ", 1987:2017),
            frames_per_second = 5,
            file_out = paste0(p_dat_derived, name, "_age_animation.gif"))
toc()

```

```{r plot-length}
length
dt[, .N, by = andcover1987]
# out of 
11550730 + # 1 (grassland or woody vegetation)
  8135598 # 0 (crop) 
19686328 # 19 M cells (19,686,328)
dt # 8,290,074 of them were abandoned at some point (even just fallowed)
nrow(dt)/19686328 * 100 # 42.11 %

summary(length[[1]])
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 1.000   2.000   4.000   6.617  10.000  30.000

length[length >= 3, summary(length)]
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 3.000   4.000   7.000   9.596  14.000  30.000 

length[length >= 5, summary(length)]
   # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   # 5.00    6.00   10.00   12.01   15.00   30.00

object_size(length)
object_size(dt)
object_size(dt_diff)

hist(length[[1]], main = "Histogram of Length of Time Abandoned \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")


# rasters:
plot(s[[1]], main = "Shaanxi 1987", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
plot(s[[31]], main = "Shaanxi 2017", breaks = c(0, plot_cols$breaks), col = plot_cols$color)


```
```{r plot-trajectory-per-pixel}
ncell(bt)
# subset the data.table, for plotting
sub <- bs_dt[1:10, -c(1,2)]
sub[, pixel := c(1:10)]

sub <- dt[1:10, -c(1,2)]
sub

names(sub) <- gsub("y", "", names(sub))
sub[, pixel := c(1:10)]



sub_melt <- melt(sub, id.vars = "pixel", 
                 variable.name = "year", 
                 value.name = "land_use", na.rm = TRUE)

sub_melt$year <- gsub("y", "", sub_melt$year)

str(sub_melt)

# set colors for plotting
show_col(terrain.colors(9))

lc_cols <- scale_color_manual(name = "Land Cover",
                     labels = c("1" = "1. Non-veg",
                                "2" = "2. Woody veg",
                                "3" = "3. Crop",
                                "4" = "4. Grassland"),
                     values = c("1" = "gray80",
                                "2" = terrain.colors(9)[1], # dark green
                                "3" = terrain.colors(9)[5], # gold
                                "4" = terrain.colors(9)[3] # light green
                                )
                     ) 

# this plot shows the land-use trajectories of 10 individual pixels.
gg_10_px_traj <- ggplot(data = sub_melt, 
                        mapping = aes(x = year, y = land_use, group = pixel)) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  geom_line(mapping = aes(color = factor(land_use)), size = 2) +
  facet_grid(rows = vars(pixel), scales = "free_x", switch = "x") + 
  ylim(1, 4) + lc_cols

gg_10_px_traj
#       1. Non-vegetated area (e.g. water, urban, barren land)
#       2. Woody vegetation
#       3. Cropland 
#       4. Herbaceous land (e.g. grassland)


```