---
title: "Figures"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r initialize}
source("scripts/0_start.R")
```

```{r basemaps}
source("")
```


```{r load-data}
# Land use class codes:
#       1. Non-vegetated area (e.g. water, urban, barren land)
#       2. Woody vegetation
#       3. Cropland 
#       4. Herbaceous land (e.g. grassland)

bs <- brick(paste0(p_dat, "Abandonment/belarus_small.tif"))

# -------------------------- rasters --------------------------- #
# raw rasters
s <- brick(paste0(p_dat, "Abandonment/shaanxi.tif"))
b <- brick(paste0(p_dat_derived, "belarus.tif")) # merged version

names(s)
names(b)
# update names

# age
s_age_r <- brick(paste0(p_dat_derived, "shaanxi_age.tif"))
b_age_r <- brick(paste0(p_dat_derived, "belarus_age.tif"))

# update year names 1987 - 2017
names(s) <- paste0("y", 1987:2017)
names(b) <- paste0("y", 1987:2017)
names(s_age_r) <- paste0("y", 1987:2017)
names(b_age_r) <- paste0("y", 1987:2017)

# data.tables
b_age <- fread(input = paste0(p_dat_derived, "belarus_age.csv"))
names(b_age)
s_age <- fread(input = paste0(p_dat_derived, "shaanxi_age.csv"))


b_length <- fread(input = paste0(p_dat_derived, "belarus_length.csv"))
s_length <- fread(input = paste0(p_dat_derived, "shaanxi_length.csv"))

b_max_length <- fread(input = paste0(p_dat_derived, "belarus_max_length.csv"))
s_max_length <- fread(input = paste0(p_dat_derived, "shaanxi_max_length.csv"))

# original data
s_dt <- fread(input = paste0(p_dat_derived, "shaanxi.csv"))
names(s_dt) <- gsub(pattern = "andcover", replacement = "y", names(s_dt))

b_dt <- fread(input = paste0(p_dat_derived, "belarus.csv")) # caution - huge file! 8.4 GB at least. 
```


```{r simple-plots}
# define color palette for plotting:
# 1. Non-veg
# 2. Woody veg
# 3. Crop
# 4. Grassland
plot_cols <- data.frame(
  color = c("gray80", # gray, 1. Non-veg
            terrain.colors(9)[1], # dark green, 2. Woody veg
            terrain.colors(9)[5], # gold, 3. Crop
            terrain.colors(9)[3] # light green, 4. Grassland
               ),
  name = c("1. Non-veg", "2. Woody veg", "3. Crop", "4. Grassland"),
  breaks = c(1, 2, 3, 4))

plot_cols_new <- c("gray80", # gray, 1. Non-veg
               terrain.colors(9)[5], # gold, 2 (formerly 3) Crop
               terrain.colors(9)[3], # light green, 3 (formerly 4) Grassland
               terrain.colors(9)[1]  # dark green, 4 (formerly 2) Woody veg
               )

plot_breaks <- c(0, 1, 2, 3, 4)

# show_col(terrain.colors(20))
# show_col(topo.colors(20))
# show_col(cm.colors(20))
# 
# show_col(plot_cols)
# show_col(plot_cols[c(1, 3, 2)])


show_col(plot_cols) # (topleft = 1, topright = 2, bottomleft = 3, bottomright = 4)
# gray,         1. Non-veg
# dark green,   2. Woody veg
# gold,         3. Crop
# light green,  4. Grassland



# -------------------------- plot raw data --------------------------- #
plot(b$y1987, main = "Belarus 1987", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

plot(b$y2017, main = "Belarus 2017", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

# ---------------------- plot abandonment age ---------------------- #
plot(b_age_r$y2017, main = "Belarus Age of Abandonment 2017")
plot(b_age_r[[28:31]])



# -------------------------- animate --------------------------- #
# --------------
# https://www.rdocumentation.org/packages/raster/versions/3.1-5/topics/animate

animate(bt, pause = 0.5, zlim = c(1, 4), maxpixels=5000, n=1,
        breaks = c(0, plot_cols$breaks), col = plot_cols$color)

```

```{r exploratory-stats}
# explore some stats:
s_length
b_length
s_length[, .N, by = length]
b_length[, .N, by = length]

```
```{r distill-length-data}
s_length[, site := "shaanxi"]
b_length[, site := "belarus"]

length_all <- rbindlist(list(s_length, b_length))
object_size(length_all)

dat_mean_length <- length_all[, .(mean_length = mean(length)), by = site]
dat2_mean_length <- length_all[length >= 5, .(mean_length_thr5 = mean(length)), by = site]
dat_mean_length <- merge(dat_mean_length, dat2_mean_length, by = "site", sort = FALSE)
dat_mean_length

# can also calculate the mean length from the distilled dat
sum((b_distill$length * b_distill$freq)) / sum(b_distill$freq)


# to use with ggplot, first distill the data

b_length_distill <- b_length[, .(freq = .N), by = length]
b_length_distill[, site := "belarus"]
s_length_distill <- s_length[, .(freq = .N), by = length]
s_length_distill[, site := "shaanxi"]

length_distill <- rbind(b_length_distill, s_length_distill)

b_max_length_distill <- b_max_length[, .(freq = .N), by = max_length]
b_max_length_distill[, site := "belarus"]
s_max_length_distill <- s_max_length[, .(freq = .N), by = max_length]
s_max_length_distill[, site := "shaanxi"]
max_length_distill <- rbind(b_max_length_distill, s_max_length_distill)


```

```{r lc-abn-area-over-time}
s_dt[, .N, by = .(y1987)] #
s_dt[, .N, by = .(y2017)] #

s_dt[, .N, by = .(y1987, y1988)] #
s_dt[, table(y1987)]

grep("x$|y$", names(s_dt), value = TRUE, invert = TRUE)

s_dt[, -c("x", "y")]
s_dt[, .N, by = c(paste0("y", 1987:2017))] #

s_dt[, .N, by = .(y1987)][order(get("y1987"))]
DT <- s_dt[, .N, by = .(y1987)][order(get("y1987"))] %>% 
  as_tibble()

DT
i <- "y1987"
rename(DT, "lc" = i, 
           eval(i) = "N")
# s_dt[, c("i", "freq") := NULL]


# ------------- calculate area raster ---------------- #
s_area <- raster::area(s$y2017) # area in km2
res(s_area)[1] * # resolution of the raster, in degrees (lat/long)
  100 * # ~100-110 km per degree 
  1000 # 1000 m/km = 26.95 m resolution

plot(s_area)

summary(getValues(s_area))
median(getValues(s_area)) # 0.0006972 km2. 
median(getValues(s_area)) * 100 / 1 # 100 ha/km2

# median pixel size is 697 m2, 0.0697 ha, or 0.000697 km2. 
median(getValues(s_area)) * # km2
  100 * # 100 ha per km2 
  10000 # m2 per ha

# the difference between minimum and maximum cell size, in m2
(max(getValues(s_area)) - 
    min(getValues(s_area))
  ) * # in km2
  1000^2 # m2 / km 2


# abandoned area over time
s_age_r
plot(s_age_r$y2017)
plot(s_age_r$y2017 > 0)
cellStats((s_age_r$y2017 > 0), "sum")

s_age[y2017 > 0, .N] # the total number of pixels with non-zero abandonment ages in the year 2017

s_age[, lapply(.SD, mean)] # mean age of abandonment over time.
s_age[y1988 > 0, .N] # count of "abandoned" cells in a particular year
s_age[get("y2017") > 0, .N]
s_age[y2017 > 0, .N]


# calculate areas for lc and abn manually
lc_area_s <- cc_total_area_per_lc(land_cover_dt = s_dt, area_raster = s_area)
abn_area_s <- cc_calc_abn_area(s_age, s_area)
area_s <- rbind(lc_area_s, abn_area_s)



# -------------------------------------------------------------- #
# -------------------------------------------------------------- #
# ------------- calculate total area per lc ---------------- #
area_s <- cc_calc_area_per_lc_abn(land_cover_dt = s_dt, 
                                  abn_age_dt = s_age, 
                                  land_cover_raster = s$y2017)

# ------------- plot ---------------- #
gg_lc_abn_area_s <- ggplot(data = area_s, aes(year, area_ha)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  labs(y = expression("Area  (10"^{6}*" ha)") , 
       x = "Year", 
       title = "Area by Land Cover, with Abandonment",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Land Cover") + 
  geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                          group = lc, color = lc),
            size = 1.2)

gg_lc_abn_area_s

# filter to include only subsets
gg_lc_abn_area_s %+% filter(area_s, lc == "Abandoned") + labs(title = "Abandoned Area")
gg_lc_abn_area_s %+% filter(area_s, lc != "Abandoned")

gg_lc_abn_area_s
gg_abn_area_s

gg_lc_abn_area_s2
gg_lc_abn_area_s



cc_save_plot_lc_abn_area(df = area_s, subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "s")

```


```{r abandonment-persistence}
s_age[get(paste0("y", 1987:2017)[2]) > 0]
s_age[y1988 > 0]

persist_l <- lapply(1:30, FUN = function(j) {
  c(
    sapply(1:(31 - j), FUN = function(i) {
      s_age[get(paste0("y", 1987:2017)[i + j]) == i, .N]
      }),
    rep(NA, j)
    )
  }
)

# ----------------------- see functions in _util_dt_filter_functions ------------------------------------ #

persistence_count_long <- cc_calc_persistence(age_dt = s_age, 
                                               land_cover_raster = s$y2017, 
                                               stat_proportion = FALSE,
                                               pivot_to_long)

# pick up here, and write up a function to save persistence plots, based on whether count, pivot, etc.

persistence_count <- cc_calc_persistence(
  s_age, stat = "count" = FALSE, pivot_to_long = FALSE)

persistence_count_long_na_first <- cc_calc_persistence(
  s_age, stat = "count", pivot_to_long = TRUE, NA_first = TRUE)

persistence_percent_long_na_first <- cc_calc_persistence(s_age, NA_first = TRUE)
persistence_percent_long <- cc_calc_persistence(s_age)
persistence_percent <- cc_calc_persistence(s_age, pivot_to_long = FALSE)


# ----------------------------------- plot ------------------------------------------------- #

# plot the count of pixels abandoned (or age 1) in each year. This shows that over time, a greater amount of land is abandoned at once.
ggplot(data = filter(persistence_count_long, time_abn == 1)) + 
  theme_classic() + 
  geom_point(mapping = aes(x = year_abn, y = count, color = year_abn))

# raw counts
gg_abn_decay_count <- ggplot(data = persistence_count_long, aes(time_abn, count)) + 
  theme_classic() + 
  geom_line(mapping = aes(x = time_abn, y = count,
                          group = year_abn, color = year_abn), 
            size = 1.25
            ) + 
  labs(y = expression("Count of pixels abandoned") , 
       x = "Years since initial abandonment", 
       title = "Persistence of Abandoned Land",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Year Abandoned") + 
  scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom")

# as percentage
gg_abn_decay <- ggplot(data = persistence_percent_long, aes(time_abn, prop_remaining)) + 
  theme_classic() + 
  geom_line(mapping = aes(x = time_abn, y = prop_remaining,
                          group = year_abn, color = year_abn), 
            size = 1.25
            ) + 
  labs(y = expression("Proportion remaining abandoned (%))") , 
       x = "Years since initial abandonment", 
       title = "Persistence of Abandoned Land",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Year Abandoned") + 
  scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom")

gg_abn_decay_na_first <- ggplot(data = persistence_percent_long_na_first, 
                                aes(year, prop_remaining)) + 
  theme_classic() + 
  geom_line(mapping = aes(x = year, y = prop_remaining,
                          group = year_abn, color = year_abn), 
            size = 1.25
            ) + 
  labs(y = expression("Proportion remaining abandoned (%))") , 
       x = "Year", 
       title = "Persistence of Abandoned Land",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Year Abandoned") + 
  scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom") + 
  scale_x_continuous(n.breaks = 10)

gg_abn_decay_count_na_first <- ggplot(data = persistence_count_long_na_first, 
                                      aes(year, count)) + 
  theme_classic() + 
  geom_line(mapping = aes(x = year, y = count,
                          group = year_abn, color = year_abn), 
            size = 1.25
            ) + 
  labs(y = expression("Area abandoned (10"^{6}*" ha)") , 
       x = "Year", 
       title = "Persistence of Abandoned Land",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Year Abandoned") + 
  scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom") + 
  scale_x_continuous(n.breaks = 10)

gg_abn_decay
gg_abn_decay_count
gg_abn_decay_na_first


cc_save_plot_abn_persistence <- function(df, subtitle, outfile_label) {
  
  gg_lc_abn_area <- ggplot(data = df, aes(year, area_ha)) +
    theme_classic() +
    # theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
    labs(y = expression("Area  (10"^{6}*" ha)") , 
         x = "Year", 
         title = "Area by Land Cover, with Abandonment",
         subtitle = subtitle,
         color = "Land Cover") + 
    geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                            group = lc, color = lc),
              size = 1.2) + 
    scale_x_continuous(n.breaks = 10)
  
  # save
  png(filename = paste0("/Users/christophercrawford/Google Drive/_Projects/abandonment_trajectories/output/plots/lc_abn_area_", 
                        outfile_label, ".png"), 
      width = 7, height = 5, units = "in", res = 400)
  
  print(gg_lc_abn_area)
  dev.off()
}

```

```{r abn-gain-loss-area}
# calculate the abandonment area turnover
abn_area_change_s <- cc_calc_abn_area_diff(age_dt = s_age, area_raster = s_area)


# gain, loss, and net change in abandoned area, over time
gg_abn_area_change_s <- ggplot() + 
  theme_classic() + 
  geom_col(data = filter(abn_area_change_s, direction != "net"),
           mapping = aes(x = year, y = area_ha / (10^3), 
                         group = direction, fill = direction)) + 
  geom_line(data = filter(abn_area_change_s, direction == "net"),
           mapping = aes(x = year, y = area_ha / (10^3), color = "Net Change in Area"),
           size = 1.5) + 
  labs(y = expression("Change in area abandoned (10"^{3}*" ha)"), 
       x = "Year", 
       title = "Change in Area of Abandoned Land",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       fill = NULL, #"Change in Area",
       color = NULL) + 
  scale_color_manual(values = c("black"),
                     labels = "Net Change in Area") + 
  scale_fill_manual(values = brewer_pal(palette = "Greens")(5)[3:2],
                    labels = c("Area Gained", "Area Lost")) + 
  theme(legend.position = "bottom")

gg_abn_area_change_s


# save to file
png(filename = paste0(p_output, "plots/abn_area_change_s.png"), 
    width = 7, height = 5, units = "in", res = 400)
print(gg_abn_area_change_s)
dev.off()

```

```{r abn-area-by-age-class}

gg_abn_area_s <- ggplot(data = filter(area_s, lc == "Abandoned"), 
                     aes(year, area_ha)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  labs(y = expression("Area  (10"^{6}*" ha)") , 
       x = "Year", 
       title = "Area of Abandoned land",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Land Cover") + 
  geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                          group = lc, color = lc))

gg_lc_abn_area_s
gg_abn_area_s

```


```{r histograms}
# plot histograms
# beware... because of the way the bins are determined, the default histogram automatically lumps 1 and 2 together. better to first distill the data and use ggplot 
hist(s_length[[1]], main = "Histogram of Length of Time Abandoned \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")

hist(b_length[[1]])

hist(length_all[site == "shaanxi", length], main = "Histogram of Abandonment Period Lengths \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")

hist(length_all[site == "belarus", length], main = "Histogram of Abandonment Period Lengths \n Belarus/Russia", xlab = "Time (years)")

hist(b_length[[1]], main = "Histogram of Abandonment Period Lengths \n Belarus/Russia", xlab = "Time (years)")
toc()

hist(b_length[[1]], main = "right = TRUE")
hist(b_length[[1]], right = FALSE, main = "right = FALSE")



# ggplots
# both site histograms
dat
length_plot <- ggplot(data = distill) + 
  labs(title = "Histogram of time abandoned across all individual periods of abandonment") +
  xlab("Time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) +
  geom_col(mapping = aes(x = length, y = freq/(10^6)), fill = "gray50") +
  facet_grid(rows = vars(site), scales = "free") +
  geom_vline(xintercept=5, linetype="dashed", 
             color = "red", size = 0.75) +
  geom_vline(xintercept=20, linetype="dashed", color = "dark green", size = 0.75) +
  theme_classic()


# max_length
max_length_plot <- ggplot(data = max_distill) + 
  labs(title = "Histogram of maximum time abandoned per pixel") +
  xlab("Maximum time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) + 
  geom_col(mapping = aes(x = max_length, y = freq/(10^6)), fill = "gray50") +
  facet_grid(rows = vars(site), scales = "free") +
  geom_vline(xintercept=5, linetype="dashed", 
             color = "red", size = 0.75) +
  geom_vline(xintercept=20, linetype="dashed", color = "dark green", size = 0.75) +
  theme_classic()


length_plot
max_length_plot
dat




# just belarus
ggplot(data = b_distill) + 
  geom_col(mapping = aes(x = length, y = freq), fill = "black") +
  theme_classic()

ggplot(data = b_length, aes(length)) + 
  geom_histogram() +
  theme_classic() # took forever!! Beware...
```

```{r save-age-histograms}

# all lengths
png(filename = paste0(p_output, "plots/length_hist.png"), 
    width = 7, height = 5, units = "in", res = 400)
print(length_plot)
dev.off()

# max lengths
png(filename = paste0(p_output, "plots/max_length_hist.png"), 
    width = 7, height = 5, units = "in", res = 400)
print(max_length_plot)
dev.off()

```



```{r pnv-habitat-lu-age-plot}
pdf(file = paste0(p_output, "plots/pnv-habitat-lu-age.pdf"),
    width = 9, height = 5.5)

# Set plot layout
# layout(mat = matrix(1:8, nrow = 2, ncol = 4),
#        heights = c(1.5, 1.5),    # Heights of the two rows
#        widths = c(2, 2, 2, 2))     # Widths of the two columns
# layout.show(8)

# layout(mat = matrix(1:8, nrow = 2, ncol = 4, byrow = TRUE),
#        heights = c(1.5, 1.5),    # Heights of the two rows
#        widths = c(2, 2, 2, 2))     # Widths of the two columns
# layout.show(8)

par(mfrow = c(2, 4),
    oma = c(0,0,0,1))
maxpixels <- 3000000

# --------------------------------------- #
# ------------ Shaanxi ------------------ #
# --------------------------------------- #

# ------------- potential natural vegetation ---------------- #
plot(s_pnv, maxpixels = 100000, main = "Shaanxi, PNV",
     breaks = c(0, filter(pnv_table, Number %in% unique(values(s_pnv)))$Number),
     col = filter(pnv_table, Number %in% unique(values(s_pnv)))$Color)

legend("topleft", 
       legend = filter(pnv_table, Number %in% unique(values(s_pnv)))$Name, 
       fill = filter(pnv_table, Number %in% unique(values(s_pnv)))$Color,
       cex = 0.6, inset = 0)


# ------------- habitat types ---------------- #
plot(s_habitat, main = "Shaanxi, Habitat Types",
     breaks = c(-1, 
                filter(habitat_table, Number %in% unique(values(s_habitat)))$Number),
     col = filter(habitat_table, Number %in% unique(values(s_habitat)))$Color,
     maxpixels = maxpixels)

legend("topleft", 
       legend = filter(habitat_table, Number %in% unique(values(s_habitat)))$Name, 
       fill = filter(habitat_table, Number %in% unique(values(s_habitat)))$Color,
       cex = 0.6, inset = 0)

# ------------- raw land use data ---------------- #
plot(s$y2015, main = "Shaanxi 2015", 
     breaks = c(0, plot_cols$breaks), col = plot_cols$color,
     maxpixels = maxpixels)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

# ------------- abandonment age ---------------- #
plot(s_age_r$y2017, main = "Shaanxi, 2017: \nTime abandoned (years)",
     maxpixels = maxpixels)


# --------------------------------------- #
# ------------ Belarus ------------------ #
# --------------------------------------- #

# ------------- potential natural vegetation ---------------- #
plot(b_pnv, maxpixels = 100000, main = "Belarus, PNV",
     breaks = c(0, filter(pnv_table, Number %in% unique(values(b_pnv)))$Number),
     col = filter(pnv_table, Number %in% unique(values(b_pnv)))$Color)

legend("bottomleft", 
       legend = filter(pnv_table, Number %in% unique(values(b_pnv)))$Name, 
       fill = filter(pnv_table, Number %in% unique(values(b_pnv)))$Color,
       cex = 0.6, inset = 0)

# ------------- habitat types ---------------- #
plot(b_habitat, main = "Belarus, Habitat Types",
     breaks = c(-1, 
                filter(habitat_table, Number %in% unique(values(b_habitat)))$Number),
     col = filter(habitat_table, Number %in% unique(values(b_habitat)))$Color,
     maxpixels = maxpixels)

legend("bottomleft", 
       legend = filter(habitat_table, Number %in% unique(values(b_habitat)))$Name, 
       fill = filter(habitat_table, Number %in% unique(values(b_habitat)))$Color,
       cex = 0.6, inset = 0)


# ------------- raw land use data ---------------- #
plot(b$y2015, main = "Belarus 2015", 
     breaks = c(0, plot_cols$breaks), col = plot_cols$color,
     maxpixels = maxpixels)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)


# ------------- abandonment age ---------------- #
plot(b_age_r$y2017, main = "Belarus, 2017: \nTime abandoned (years)",
     maxpixels = maxpixels)


dev.off()

```



