---
title: "Biodiversity development"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r initialize}
source("scripts/0_start.R")
```

```{r pnv}
# load PNV
pnv <- raster(paste0(p_dat, "/Habitats/PNV/Hengl_2018_PNV/1km/pnv_biome.type_biome00k_c_1km_s0..0cm_2000..2017_v0.1.tif"))

# color palette information
pnv_table <- read_csv(paste0(p_dat, "/Habitats/PNV/Hengl_2018_PNV/1km/pnv_biome.type_biome00k_c_1km_s0..0cm_2000..2017_v0.1.tif.csv"))
pnv_col <- rgb(pnv_table$R, pnv_table$G, pnv_table$B, maxColorValue = 255)

hist(pnv, maxpixels = 1000)
extent(s$y2017)
plot(extent(s$y2017))
plot(pnv, maxpixels = 1000)

# plot PNV map, with 
plot(pnv, maxpixels = 100000,
     main = "PNV, Hengl et al. 2018",
     breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_col, legend = FALSE)
legend("top", legend = pnv_table$New.global.consolidated.biome.scheme[1:10], 
       fill = pnv_col[1:10], cex = 0.5, inset = 0)
legend("bottom", legend = pnv_table$New.global.consolidated.biome.scheme[11:21], 
       fill = pnv_col[11:21], cex = 0.5, inset = 0)

# shaanxi
plot(pnv, maxpixels = 100000,
     ext = extent(s$y2017),
     breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_col)

# belarus
plot(pnv, maxpixels = 100000,
     ext = extent(b$y2017),
     breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_col)


# crop:
tic()
s_pnv <- crop(pnv, extent(s$y2017))
toc()
plot(s_pnv, breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_col)
unique(values(s_pnv))
filter(pnv_table, Number %in% unique(values(s_pnv)))


plot(s_pnv, maxpixels = 100000,
     breaks = c(0, filter(pnv_table, Number %in% unique(values(s_pnv)))$Number), # note, you need a 0 at the beginning of the breaks
     col = rgb(filter(pnv_table, Number %in% unique(values(s_pnv)))$R, 
               filter(pnv_table, Number %in% unique(values(s_pnv)))$G, 
               filter(pnv_table, Number %in% unique(values(s_pnv)))$B, 
               maxColorValue = 255)
     )
legend("bottom", 
       legend = filter(pnv_table, Number %in% 
                         unique(values(s_pnv)))$New.global.consolidated.biome.scheme, 
       fill = rgb(filter(pnv_table, Number %in% unique(values(s_pnv)))$R, 
               filter(pnv_table, Number %in% unique(values(s_pnv)))$G, 
               filter(pnv_table, Number %in% unique(values(s_pnv)))$B, 
               maxColorValue = 255),
       cex = 0.5, inset = 0)
legend("right", legend = ,
       fill = )




plot(pnv, maxpixels = 100000,
     ext = extent(s$y2017))
cellStats(pnv, ext = extent(s$y2017))

# what habitat types are these?



# explore

# plot

plot(b_age_r$y2017, main = "Belarus, abn age, 2017")
plot(s_age_r$y2017, main = "Shaanxi, abn age, 2017")

```

```{r basemaps}
# plot world
plot(world_sf$geometry)

eastern_europe <- ne_countries(scale = 110, returnclass = "sf", continent = "europe")
plot(eastern_europe$geometry)
st_crs(eastern_europe$geometry)
eastern_europe$geometry %>%
  st_transform(., crs("+proj=longlat +ellps=WGS84 +lon_0=70")) %>%
  plot(border = "red")

crs(usa)

china <- ne_countries(scale = 110, returnclass = "sf", country = "china")
plot(china$geometry, graticule = TRUE, axes = TRUE)
plot(usa$geometry, graticule = TRUE, axes = TRUE)

l <- eastern_europe$geometry %>% st_wrap_dateline()
l <- st_transform(eastern_europe$geometry, "+proj=laea +lon_0=30")
l %>%
  plot()

plot(box$geometry)
ecoregions

r <- b_age_r$y2017
r
rt <- projectRaster(r, crs = "+proj=laea")
plot(projectRaster(extent(b_age_r), crs = "+proj=laea"), add = T, col = "red")
plot(extent(s_age_r), add = T, col = "red")



```


```{r RS-AOH-tester}
library(sf)
AOH <- st_read("/Users/christophercrawford/Google Drive/_Projects/data/Bd/AOH/reptilia_AOH/reptilia.shp")

AOH %>% st_drop_geometry() %>% as_tibble()
object_size(AOH)
names(AOH)
head(AOH)
st_crs(AOH)



# plot
AOH %>% 
  filter(binom == "Archaius_tigris") %>% 
  st_geometry() %>% 
  plot()

AOH %>% 
  st_geometry() %>% 
  plot(add = TRUE)

plot(ne_countries()) # or all sub national level bodies plot(ne_states())

crs(ne_countries())

# Create template raster by extending the input raster (mask) to the extent of the input polygons.
mask_filled <- mask
mask_filled[is.na(mask_filled)] <- 0 # replace NAs with 0s

projection <- crs(AOH) # note, seems to work better than st_crs().

# make a template raster
mask <- raster()
res(mask) <- 0.01


# values(mask) <- 0 # If you want, you can add values to the raster. You don't have to though, and it just makes the raster HUGE at this resolution (4.8 GB)
# writeRaster(mask, "mask.tif") # if you add values, you'll need to just write it to your machine, otherwise you'll quickly run out of memory, as the fasterize layer will be the same size.  


AOH_r <- fasterize(AOH, mask, fun = "sum") # field = NULL by default, which gives every polygon a value of 1

# in the event that you want to build a raster based on 
template_raster <- extend(small_mask, extent(as.Spatial(sf_file)), value = 0)




# fasterize


  
```

```{r sparse}
library(sf)
library(raster)

AOH <- st_read("/Users/christophercrawford/Google Drive/_Projects/data/Bd/AOH/reptilia_AOH/reptilia.shp")

# check it out
AOH %>% 
  filter(binom == "Archaius_tigris") %>% 
  st_geometry() %>% 
  plot()

AOH %>% 
  st_geometry() %>% 
  plot(add = TRUE)
# tiny lil guys, eh?



# -------------------
# First, make a template raster

mask <- raster()
res(mask) <- 0.01


# values(mask) <- 0 # If you want, you can add values to the raster. You don't have to though, and it just makes the raster HUGE at this resolution (4.8 GB)
# writeRaster(mask, "mask.tif") # if you add values, you'll need to just write it to your machine, otherwise you'll quickly run out of memory, as the fasterize layer will be the same size.  


# -------------------
#  Fasterize: 

AOH_r <- fasterize(AOH, mask, fun = "sum") # field = NULL by default, which gives every polygon a value of 1

plot(AOH_r) # again.... tiny lil guys!




# -------------------
# Notes:

# If you aren't already familiar, these are great packages for basemaps:
install.packages("rnaturalearth")
devtools::install_github("ropensci/rnaturalearthdata")
devtools::install_github("ropensci/rnaturalearthhires")
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)

plot(ne_countries())  # nice!
# plot(ne_states()) # or all sub national level bodies with this one 



# if you need to reproject the mask before you fasterize, I think raster works best with: 
crs(AOH) # note, seems to work better than st_crs().

# in the event that you want to build a raster based on a smaller existing one
template_raster <- extend(small_mask, extent(as.Spatial(sf_file)), value = 0)



```

