---
title: "Biodiversity development"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r initialize}
source("scripts/0_start.R")
```

# Habitats

```{r pnv}
# load PNV
pnv <- raster(paste0(p_dat, "/Habitats/PNV/Hengl_2018_PNV/1km/pnv_biome.type_biome00k_c_1km_s0..0cm_2000..2017_v0.1.tif"))

# Resolution
res(pnv) * 110 # = 0.9167 km grid (~ 1 km)


# color palette information
pnv_table <- read_csv(paste0(p_dat, "/Habitats/PNV/Hengl_2018_PNV/1km/pnv_biome.type_biome00k_c_1km_s0..0cm_2000..2017_v0.1.tif.csv"))
pnv_table <- pnv_table %>%
  mutate(Color = rgb(R, G, B, maxColorValue = 255)) %>%
  rename(Name = New.global.consolidated.biome.scheme)


hist(pnv, maxpixels = 1000)
extent(s$y2017)
plot(extent(s$y2017))
plot(pnv, maxpixels = 1000)

# plot PNV map, with 
plot(pnv, maxpixels = 100000,
     main = "PNV, Hengl et al. 2018",
     breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_table$Color, legend = FALSE)
legend("top", legend = pnv_table$Name[1:10], 
       fill = pnv_table$Color[1:10], cex = 0.5, inset = 0)
legend("bottom", legend = pnv_table$Name[11:21], 
       fill = pnv_table$Color[11:21], cex = 0.5, inset = 0)

# shaanxi
plot(pnv, maxpixels = 100000,
     ext = extent(s$y2017),
     breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_table$Color)

# belarus
plot(pnv, maxpixels = 100000,
     ext = extent(b$y2017),
     breaks = c(0, pnv_table$Number), # note, you need a 0 at the beginning of the breaks
     col = pnv_table$Color)


# crop:
s_pnv <- crop(pnv, extent(s$y2017))
b_pnv <- crop(pnv, extent(b$y2017))

sort(unique(values(s_pnv)))
sort(unique(values(b_pnv)))
filter(pnv_table, Number %in% unique(values(s_pnv)))
filter(pnv_table, Number %in% unique(values(b_pnv)))

c(0, filter(pnv_table, Number %in% unique(values(s_pnv)))$Number)
pnv_table$Color
pnv_table

# shaanxi
par(mfrow = c(2,2))
plot(s_pnv, maxpixels = 100000, main = "Shaanxi, PNV",
     breaks = c(0, filter(pnv_table, Number %in% unique(values(s_pnv)))$Number),
     col = filter(pnv_table, Number %in% unique(values(s_pnv)))$Color)

legend("topleft", 
       legend = filter(pnv_table, Number %in% unique(values(s_pnv)))$Name, 
       fill = filter(pnv_table, Number %in% unique(values(s_pnv)))$Color,
       cex = 0.6, inset = 0)


# belarus
plot(b_pnv, maxpixels = 100000, main = "Belarus, PNV",
     breaks = c(0, filter(pnv_table, Number %in% unique(values(b_pnv)))$Number),
     col = filter(pnv_table, Number %in% unique(values(b_pnv)))$Color)

legend("bottomleft", 
       legend = filter(pnv_table, Number %in% unique(values(b_pnv)))$Name, 
       fill = filter(pnv_table, Number %in% unique(values(b_pnv)))$Color,
       cex = 0.6, inset = 0)


# what habitat types are these?

# area in each category, in km2 \\ Shaanxi
s_pnv_area <- pnv_table %>%
  filter(Number %in% unique(values(s_pnv))) %>%
  select(Number, Name) %>%
  mutate(
    area_percent = (table(getValues(s_pnv))/ncell(s_pnv))*100, # percentage in each
    area_km2 = 
      length(raster::area(s_pnv)) * 
      median(raster::area(s_pnv), na.rm = TRUE) * 
      area_percent/100
  )
s_pnv_area # 
# < 0.05 % in 9 (cool mixed forest) and 27 (desert)
# 96% in steppe
# 3.82% in temperate deciduous broadleaf forest

# area in each category, in km2 \\ Belarus
b_area <- pnv_table %>%
  filter(Number %in% unique(values(b_pnv))) %>%
  select(Number, Name) %>%
  mutate(
    area_percent = (table(getValues(b_pnv))/ncell(b_pnv))*100, # percentage in each
    area_km2 = 
      length(raster::area(b_pnv)) * 
      median(raster::area(b_pnv), na.rm = TRUE) * 
      area_percent/100
  )

b_area
# 2/3 in 9, or "cool mixed forest"
# 1/3 in 15, or "cold evergreen needleleaf forest"


# plot

plot(b_age_r$y2017, main = "Belarus, abn age, 2017")
plot(s_age_r$y2017, main = "Shaanxi, abn age, 2017")
```

Which pnv map should we use? The published 1 km map, or the 250 m map?
```{r pnv-250m}
pnv_250 <- raster(paste0(p_dat, "/Habitats/PNV/Hengl_2018_PNV/250m/pnv_biome.type_biome00k_c_250m_s0..0cm_2000..2017_v0.2.tif"))

# Resolution
res(pnv) * 110 # = 0.9167 km grid (~ 1 km)
res(pnv_250) * 110 # = 0.229 km grid (~ 250 m)

# color palette information
pnv_250_table <- read_csv(paste0(p_dat, "Habitats/PNV/Hengl_2018_PNV/250m/pnv_biome.type_biome00k_c_250m_s0..0cm_2000..2017_v0.2.tif.csv"))
pnv_table # the tables are the same
pnv_250_table == pnv_table
pnv_250_table[14, ]
pnv_table[14, ]

# crop:
s_pnv_250 <- crop(pnv_250, extent(s$y2017))
b_pnv_250 <- crop(pnv_250, extent(b$y2017))

sort(unique(values(s_pnv_250)))
sort(unique(values(b_pnv_250)))
filter(pnv_table, Number %in% unique(values(s_pnv_250)))
filter(pnv_table, Number %in% unique(values(b_pnv_250)))

# plots
# shaanxi
plot(s_pnv_250, maxpixels = 100000, main = "Shaanxi, PNV, 250 m resolution",
     breaks = c(0, filter(pnv_table, Number %in% unique(values(s_pnv_250)))$Number),
     col = filter(pnv_table, Number %in% unique(values(s_pnv_250)))$Color)

legend("topleft", 
       legend = filter(pnv_table, Number %in% unique(values(s_pnv_250)))$Name, 
       fill = filter(pnv_table, Number %in% unique(values(s_pnv_250)))$Color,
       cex = 0.6, inset = 0)

# belarus
plot(b_pnv_250, maxpixels = 100000, main = "Belarus, PNV, 250 m resolution",
     breaks = c(0, filter(pnv_table, Number %in% unique(values(b_pnv_250)))$Number),
     col = filter(pnv_table, Number %in% unique(values(b_pnv_250)))$Color)

legend("bottomleft", 
       legend = filter(pnv_table, Number %in% unique(values(b_pnv_250)))$Name, 
       fill = filter(pnv_table, Number %in% unique(values(b_pnv_250)))$Color,
       cex = 0.6, inset = 0)


# what habitat types are these?
# belarus, mostly closed mixed 

# area in each category, in km2 \\ Shaanxi
s_pnv_area_250 <- pnv_table %>%
  filter(Number %in% unique(values(s_pnv_250))) %>%
  select(Number, Name) %>%
  mutate(area_percent = (table(getValues(s_pnv_250))/ncell(s_pnv_250))*100, # percentage in each
    area_km2 = 
      length(raster::area(s_pnv_250)) * 
      median(raster::area(s_pnv_250), na.rm = TRUE) * 
      area_percent/100
  )
s_pnv_area # 
s_pnv_area_250
# < 0.05 % in 9 (cool mixed forest) and 27 (desert)
# 96% in steppe
# 3.82% in temperate deciduous broadleaf forest

# area in each category, in km2 \\ Belarus
b_area_250 <- pnv_table %>%
  filter(Number %in% unique(values(b_pnv_250))) %>%
  select(Number, Name) %>%
  mutate(area_percent = (table(getValues(b_pnv_250))/ncell(b_pnv_250))*100, # percentage in each
    area_km2 = 
      length(raster::area(b_pnv_250)) * 
      median(raster::area(b_pnv_250), na.rm = TRUE) * 
      area_percent/100
  )

b_area_250
b_area
# 2/3 in 9, or "cool mixed forest"
# 1/3 in 15, or "cold evergreen needleleaf forest"


```


```{r habitat classifications}
# level 1
habitat <- raster("/Users/christophercrawford/Google_Drive/_Projects/data/Habitats/Jung_GlobalHabitatTypes/iucn_habitatclassification_composite_lvl1_ver003.tif")

# level 2
habitat <- raster("/Users/christophercrawford/Google_Drive/_Projects/data/Habitats/Jung_GlobalHabitatTypes/iucn_habitatclassification_composite_lvl2_ver003.tif")

stack()

# color palette information #
# level 1
habitat_table <- read_delim(file = "/Users/christophercrawford/Google_Drive/_Projects/data/Habitats/Jung_GlobalHabitatTypes/iucn_habitatclassification_code_ver003/styles/level1.clr", delim = " ", col_names = c("Number", "R", "G", "B", "Opacity", "Name"))

# level 2
habitat_table <- read_delim(file = "/Users/christophercrawford/Google_Drive/_Projects/data/Habitats/Jung_GlobalHabitatTypes/iucn_habitatclassification_code_ver003/styles/level2.clr", delim = " ", col_names = c("Number", "R", "G", "B", "Opacity", "Name"))
habitat_table <- habitat_table %>%
  mutate(Color = rgb(R, G, B, maxColorValue = 255))

habitat_table[habitat_table$Name == "Forest", "Color"] <- terrain.colors(15)[1]
habitat_table[habitat_table$Name == "Shrubland", "Color"] <- terrain.colors(15)[2]
habitat_table[habitat_table$Name == "Savanna", "Color"] <- terrain.colors(15)[3]
habitat_table[habitat_table$Name == "Grassland", "Color"] <- filter(plot_cols, name == "4. Grassland")$color
habitat_table[habitat_table$Name == "Artificial", "Color"] <- filter(plot_cols, name == "3. Crop")$color

plot_cols
show_col(plot_cols$color)
show_col(habitat_table$Color)
show_col(terrain.colors(15))
terrain.colors(9)
show_col("006633")
show_col("brown")


habitat
res(habitat) * 110 # = 0.0988 km grid (~ 0.10 km, ~ 100 m)

# crop:
s_habitat <- crop(habitat, extent(s$y2017))
b_habitat <- crop(habitat, extent(b$y2017))

sort(unique(values(s_habitat)))
sort(unique(values(b_habitat)))
filter(habitat_table, Number %in% unique(values(s_habitat)))
filter(habitat_table, Number %in% unique(values(b_habitat)))


# fancy plots
par(mfrow = c(2,2))
plot(s_habitat, main = "Shaanxi, Habitat Types",
     breaks = c(-1, 
                filter(habitat_table, Number %in% unique(values(s_habitat)))$Number),
     col = filter(habitat_table, Number %in% unique(values(s_habitat)))$Color)

legend("topleft", 
       legend = filter(habitat_table, Number %in% unique(values(s_habitat)))$Name, 
       fill = filter(habitat_table, Number %in% unique(values(s_habitat)))$Color,
       cex = 0.6, inset = 0)

# compare to raw land use data
plot(s$y2015, main = "Shaanxi 2015", 
     breaks = c(0, plot_cols$breaks), 
     col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

# belarus
plot(b_habitat, main = "Belarus, Habitat Types",
     breaks = c(-1, 
                filter(habitat_table, Number %in% unique(values(b_habitat)))$Number),
     col = filter(habitat_table, Number %in% unique(values(b_habitat)))$Color)

legend("bottomleft", 
       legend = filter(habitat_table, Number %in% unique(values(b_habitat)))$Name, 
       fill = filter(habitat_table, Number %in% unique(values(b_habitat)))$Color,
       cex = 0.6, inset = 0)


# compare to raw land use data
plot(b$y2015, main = "Belarus 2015", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)



habitat_table 
# 0   Water                     
# 100 Forest                   
# 200 Savanna                 
# 300 Shrubland               
# 400 Grassland              
# 500 Wetlands (inland)       
# 600 Rocky Areas            
# 800 Desert                 
# 1400 Artificial - Terrestrial
# 1700 Unknown
unique(values(b_habitat))
table(getValues(b_habitat))/ncell(b_habitat)
plot(b_habitat, main = "Belarus Habitat classes", breaks = c(0, 100, 300, 500, 1400), col = plot_cols$color[c(2, 4, 4, 3)])


# summary stats
b_habitat_area <- habitat_table %>%
  filter(Number %in% unique(values(b_habitat))) %>%
  select(Number, 
         Name = New.global.consolidated.biome.scheme) %>%
  mutate(
    area_percent = (table(getValues(b_pnv))/ncell(b_pnv))*100, # percentage in each
    area_km2 = 
      length(raster::area(b_pnv)) * 
      median(raster::area(b_pnv), na.rm = TRUE) * 
      area_percent/100
  )

```




```{r basemaps}
# plot world
plot(world_sf$geometry)

eastern_europe <- ne_countries(scale = 110, returnclass = "sf", continent = "europe")
plot(eastern_europe$geometry)
st_crs(eastern_europe$geometry)
eastern_europe$geometry %>%
  st_transform(., crs("+proj=longlat +ellps=WGS84 +lon_0=70")) %>%
  plot(border = "red")

crs(usa)

china <- ne_countries(scale = 110, returnclass = "sf", country = "china")
plot(china$geometry, graticule = TRUE, axes = TRUE)
plot(usa$geometry, graticule = TRUE, axes = TRUE)

l <- eastern_europe$geometry %>% st_wrap_dateline()
l <- st_transform(eastern_europe$geometry, "+proj=laea +lon_0=30")
l %>%
  plot()

plot(box$geometry)
ecoregions

r <- b_age_r$y2017
r
rt <- projectRaster(r, crs = "+proj=laea")
plot(projectRaster(extent(b_age_r), crs = "+proj=laea"), add = T, col = "red")
plot(extent(s_age_r), add = T, col = "red")



```


```{r RS-AOH-tester}
library(sf)
AOH <- st_read("/Users/christophercrawford/Google_Drive/_Projects/data/Bd/AOH/reptilia_AOH/reptilia.shp")

AOH %>% st_drop_geometry() %>% as_tibble()
object_size(AOH)
names(AOH)
head(AOH)
st_crs(AOH)



# plot
AOH %>% 
  filter(binom == "Archaius_tigris") %>% 
  st_geometry() %>% 
  plot()

AOH %>% 
  st_geometry() %>% 
  plot(add = TRUE)

plot(ne_countries()) # or all sub national level bodies plot(ne_states())

crs(ne_countries())

# Create template raster by extending the input raster (mask) to the extent of the input polygons.
mask_filled <- mask
mask_filled[is.na(mask_filled)] <- 0 # replace NAs with 0s

projection <- crs(AOH) # note, seems to work better than st_crs().

# make a template raster
mask <- raster()
res(mask) <- 0.01


# values(mask) <- 0 # If you want, you can add values to the raster. You don't have to though, and it just makes the raster HUGE at this resolution (4.8 GB)
# writeRaster(mask, "mask.tif") # if you add values, you'll need to just write it to your machine, otherwise you'll quickly run out of memory, as the fasterize layer will be the same size.  


AOH_r <- fasterize(AOH, mask, fun = "sum") # field = NULL by default, which gives every polygon a value of 1

# in the event that you want to build a raster based on 
template_raster <- extend(small_mask, extent(as.Spatial(sf_file)), value = 0)




# fasterize


  
```

```{r sparse}
library(sf)
library(raster)

AOH <- st_read("/Users/christophercrawford/Google_Drive/_Projects/data/Bd/AOH/reptilia_AOH/reptilia.shp")

# check it out
AOH %>% 
  filter(binom == "Archaius_tigris") %>% 
  st_geometry() %>% 
  plot()

AOH %>% 
  st_geometry() %>% 
  plot(add = TRUE)
# tiny lil guys, eh?



# -------------------
# First, make a template raster

mask <- raster()
res(mask) <- 0.01


# values(mask) <- 0 # If you want, you can add values to the raster. You don't have to though, and it just makes the raster HUGE at this resolution (4.8 GB)
# writeRaster(mask, "mask.tif") # if you add values, you'll need to just write it to your machine, otherwise you'll quickly run out of memory, as the fasterize layer will be the same size.  


# -------------------
#  Fasterize: 

AOH_r <- fasterize(AOH, mask, fun = "sum") # field = NULL by default, which gives every polygon a value of 1

plot(AOH_r) # again.... tiny lil guys!




# -------------------
# Notes:

# If you aren't already familiar, these are great packages for basemaps:
install.packages("rnaturalearth")
devtools::install_github("ropensci/rnaturalearthdata")
devtools::install_github("ropensci/rnaturalearthhires")
library(rnaturalearth)
library(rnaturalearthdata)
library(rnaturalearthhires)

plot(ne_countries())  # nice!
# plot(ne_states()) # or all sub national level bodies with this one 



# if you need to reproject the mask before you fasterize, I think raster works best with: 
crs(AOH) # note, seems to work better than st_crs().

# in the event that you want to build a raster based on a smaller existing one
template_raster <- extend(small_mask, extent(as.Spatial(sf_file)), value = 0)



```

```{r biomes}
# use this version to match to PREDICTS
tic()
ecoregions <- st_read(paste0(p_dat, "Habitats/terr-ecoregions-TNC/tnc_terr_ecoregions.shp")) %>%
  st_make_valid()
toc() # 20 seconds about. (making the geometries valid is quick!)


# rename the column for WWF_MHTNAM to biome (this matches PREDICTS)
ecoregions <- ecoregions %>% mutate(biome = WWF_MHTNAM)
ecoregions %>% st_drop_geometry() %>% select(biome) %>% unlist(use.names = FALSE) %>% unique()

# union ecoregions within each biome
biome_names <- ecoregions %>% st_drop_geometry() %>% select(biome) %>% unlist(use.names = FALSE) %>% unique()
biome_l <- vector(mode = "list", length = 16L)
names(biome_l) <- biome_names

tic()
for(i in 1:16) {
  biome_l[[i]] <- ecoregions %>% 
    filter(biome == biome_names[i]) %>%
    st_union() %>%
    st_sf() %>%
    mutate(biome = biome_names[i])
}
toc() # took a bit of a while - maybe 60 seconds.

biomes <- bind_rows(biome_l)

# I tried aggregate, st_union, st_combine, merge, etc., and I couldn't find a simple way to dissolve an sf object based on an attribute, other than doing them all individually, then binding them back together. 


# save biomes sf file
st_write(biomes, dsn = paste0(p_dat, "Habitats/biomes.shp"))
save(biomes, file = paste0(p_dat, "Habitats/biomes.rds"))

biomes <- st_read(paste0(p_dat, "Habitats/biomes.shp"))
```

```{r plot-biomes}
# load biomes - see "biomes" chunk above
biomes <- st_read(paste0(p_dat, "Habitats/biomes.shp"))


ggplot() + theme_classic() + 
  geom_sf(data = biomes, aes(fill = biome))

# "Biomes ... are defined by The Nature Conservancy's terrestrial ecoregions of the world dataset"

# make a list of cropped biomes cropped to each site:
biomes_crop <- lapply(1:11, function(i) {
  temp <- st_crop(biomes, extent(site_r[[i]]))
  temp <- temp %>% mutate(site = site_df$site[i])
  temp
}) %>% bind_rows()

site_biome_names <- biomes_crop %>% 
  st_drop_geometry() %>% select(biome) %>% 
  arrange(biome) %>% unique() %>% .$biome

# all site - but facet_wrap doesn't work with geom_sf with free scales
ggplot() + theme_classic() + 
  geom_sf(data = biomes_crop, aes(fill = biome)) + 
  # theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  facet_wrap(vars(site))


biome_pal <- gg_color_hue(9)
names(biome_pal) <- site_biome_names

site_df
biomes_crop %>% st_drop_geometry() %>% select(biome, site) %>%
  


str_wrap(names(biome_pal), 20)

biomes_crop %>% 
  st_drop_geometry() %>% select(biome, site)
  
gg_biomes_all <-
  ggplot(data = biomes_crop, aes(fill = biome)) +
  theme_classic() + 
  geom_sf() + 
  labs(fill = NULL) +
  theme(legend.position = "right",
        legend.text = element_text(size = 7)) + 
  guides(fill = guide_legend(ncol = 2)) +
  scale_fill_manual(values = biome_pal, labels = str_wrap(names(biome_pal), 24)
                    ) + 
  facet_wrap(vars(site), labeller = as_labeller(cap_update_labels))

  
biomes_by_site <-
  lapply(1:11, function(i){
    ggplot(data = biomes_crop %>% filter(site == site_df$site[i]), aes(fill = biome)) +
      theme_classic() + 
      geom_sf() + 
      labs(fill = NULL) +
      theme(legend.position = "none",
            axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) + 
      guides(fill = guide_legend(ncol = 1)) + 
      scale_fill_manual(values = biome_pal) + 
      facet_wrap(vars(site), labeller = as_labeller(cap_update_labels))
  })


biome_legend <- ggpubr::get_legend(gg_biomes_all + 
                                     guides(fill = guide_legend(nrow = 2)) +
                                     theme(legend.position = "bottom"))

ggsave(plot = 
         plot_grid(
           plot_grid(plotlist = biomes_by_site, ncol = 4, nrow = 3),
           as_ggplot(biome_legend),
           nrow = 2, rel_heights = c(2, 0.2)),
       filename = paste0(p_plots, "biomes_by_site.pdf"), 
    width = 7.5, height = 6.75, units = "in"
)

as_ggplot(biome_legend)

# biomes_by_site[[12]] <- as_ggplot(biome_legend)

ggplot(data = biomes_crop, aes(fill = biome)) +
  theme_classic() + 
  geom_sf() + 
  # scale_fill_manual(values = biome_pal, labels = str_wrap(names(biome_pal), 20)) + 
  # facet_wrap(vars(site), labeller = as_labeller(cap_update_labels)) +
  guides(fill = guide_legend(ncol = 1)) %>% 
  ggpubr::get_legend() %>% as_ggplot()
```

```{r mn-biome}
usa <- ne_states(returnclass = "sf", country = "United States of America")
mn <- usa %>%
  filter(name == "Minnesota")

wi <- usa %>% filter(name == "Wisconsin")
plot(mn$geometry)
plot(wi$geometry)
mn_biome <- st_crop(biomes, extent(mn))
wi_biome <- st_crop(biomes, extent(wi))

ggplot() +
  theme_classic() + 
  geom_sf(data = mn_biome, aes(fill = biome))

ggplot() +
  theme_classic() + 
  geom_sf(data = wi_biome, aes(fill = biome))

ggplot() + theme_classic() + 
  geom_sf(data = mn_biome, aes(fill = biome)) +
  geom_sf(data = wi_biome, aes(fill = biome))


```


```{r biome-with-raster}
ggplot() +
  theme_classic() + 
  geom_sf(data = biomes_crop %>% filter(site == "shaanxi"), aes(fill = biome)) + 
  labs(fill = NULL) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 7)) + 
  guides(fill = guide_legend(ncol = 2)) +
  scale_fill_manual(values = biome_pal, labels = str_wrap(names(biome_pal), 24)
                    ) + 
  facet_wrap(vars(site), labeller = as_labeller(cap_update_labels)) + 
  geom_raster(age_r$shaanxi$y2017, mapping = aes(fill = y2017))


plot(biomes_crop %>% filter(site == "shaanxi") %>% select(biome))

p <- gplot(age_r$shaanxi$y2017) + 
  geom_raster(aes(fill = value)) +
  # facet_wrap(~ variable) +
  scale_fill_gradientn(colours = terrain.colors(100)) +
  coord_quickmap() 

```

