---
title: "Figures"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r initialize}
source("/Users/christophercrawford/Google_Drive/_Projects/abandonment_trajectories/scripts/0_start.R")
```

```{r set-run_label}
run_label <- "_2021-03-05"

# run_label <- "_b1"
```

```{r load-data}
# for use on cluster:
# p_dat <- "/scratch/network/clc6/abandonment_trajectories/data_derived/"
# p_dat_derived <- "/scratch/network/clc6/abandonment_trajectories/data_derived/"
# p_output <- paste0("/scratch/network/clc6/abandonment_trajectories/output/")
list.files(p_dat_derived)
list.files(p_dat)

site_df <- read.csv(file = paste0(p_dat_derived, "site_df.csv"))

0.0008
1/60/60 * 3 # 3 arc seconds
# This corresponds to about
3* 1/60/60 * 110 * 1000
bs
res(b) * 110 * 1000


# Land use class codes:
#       1. Non-vegetated area (e.g. water, urban, barren land)
#       2. Woody vegetation
#       3. Cropland 
#       4. Herbaceous land (e.g. grassland)

# testers:
bs <- brick(paste0(p_dat, "Abandonment/belarus_small.tif"))
bt <- brick(paste0(p_dat_derived, "belarus_subset.tif"))
names(bs) <- paste0("y", 1987:2017)
names(bt) <- paste0("y", 1987:2017)


# -------------------------- rasters --------------------------- #
# raw rasters
s <- brick(paste0(p_dat_derived, "input_rasters/shaanxi.tif"))
b <- brick(paste0(p_dat_derived, "input_rasters/belarus.tif")) # merged version

# age
s_age_r <- brick(paste0(p_dat_derived, "shaanxi_age.tif"))
b_age_r <- brick(paste0(p_dat_derived, "belarus_age.tif"))

# max_length
s_max_length_r <- brick(paste0(p_dat_derived, "shaanxi_max_length.tif"))
b_max_length_r <- brick(paste0(p_dat_derived, "belarus_max_length.tif"))

# update year names 1987 - 2017
names(s) <- paste0("y", 1987:2017)
names(b) <- paste0("y", 1987:2017)
names(s_age_r) <- paste0("y", 1987:2017)
names(b_age_r) <- paste0("y", 1987:2017)


# prepared input rasters (derived by Chris)
site_input_raster_files <- list.files(paste0(p_dat_derived, "input_rasters"), full.names = TRUE) %>%
  grep(".tif", ., value = TRUE) #%>% grep("age", ., value = TRUE, invert = TRUE)

lc <- lapply(seq_along(site_input_raster_files), function(i) {brick(site_input_raster_files[i])})
names(lc) <- site_df$site

# rename raster layers:
for (i in 1:11) {
  if (names(lc[i]) == "nebraska") {
    names(lc[[i]]) <- paste0("y", 1986:2018)
  } else {
    if (names(lc[i]) == "wisconsin") {
      names(lc[[i]]) <- paste0("y", 1987:2018)
    } else {
      # everything else, just 1987:2017
      names(lc[[i]]) <- paste0("y", 1987:2017)
    }}}


# abandonment age maps (produced by Chris)
age_files <- list.files(paste0(p_dat_derived, "age_rasters/", run_label), 
                        full.names = TRUE) %>%
  grep(".tif", ., value = TRUE) #%>% grep("age", ., value = TRUE, invert = FALSE)

age_r <- lapply(seq_along(age_files), function(i) {brick(age_files[i])})
names(age_r) <- site_df$site
for (i in seq_along(age_r)) {names(age_r[[i]]) <- paste0("y", 1987:2017)} # remember: these are just 1987:2017

# year of first abandonment maps (from He)
yoa_files <- list.files(paste0(p_dat, "Abandonment/year_of_abandonment/"))

# -------------------------- data.tables --------------------------- #
b_age <- fread(input = paste0(p_dat_derived, "belarus_age.csv"))
names(b_age)
s_age <- fread(input = paste0(p_dat_derived, "shaanxi_age.csv"))


b_length <- fread(input = paste0(p_dat_derived, "lengths/", "belarus_length_b1.csv"))
s_length <- fread(input = paste0(p_dat_derived, "lengths/", "shaanxi_length_b1.csv"))

b_max_length <- fread(input = paste0(p_dat_derived, "lengths/", "belarus_max_length_b1.csv"))
s_max_length <- fread(input = paste0(p_dat_derived, "lengths/", "shaanxi_max_length_b1.csv"))

# original data
s_dt <- fread(input = paste0(p_dat_derived, "shaanxi.csv"))
names(s_dt) <- gsub(pattern = "andcover", replacement = "y", names(s_dt))

b_dt <- fread(input = paste0(p_dat_derived, "input_data.tables/belarus.csv")) # caution - huge file! 8.4 GB at least. 
b_dt <- fread(input = paste0(p_dat_derived, "input_data.tables/belarus.csv"),
              select = 3,
              nrows = 200) # caution - huge file! 8.4 GB at least. 
nrow(b_dt)

env_size(ls())


# -------------------------- summarized data.frames --------------------------- #
indx <- 9
site <- site_df$site[indx] # set site:
site_label <- site_df$label[indx] # set label
blip_label <- "_b1"
load(file = paste0(p_output, "abn_dat_products", blip_label, site_label, ".rds"), verbose = TRUE)

# loads:
area_b1_s
persistence_list_b1_s
abn_area_change_b1_s

# note, on 3/4/21 I made the following changes:
# replace abn_area_change with turnover
# replace abn_area_diff with abn_diff


```

```{r simple-plots}

# -------------------------- plot raw data --------------------------- #
plot(b$y1987, main = "Belarus 1987", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)

plot(b$y2017, main = "Belarus 2017", breaks = c(0, plot_cols$breaks), col = plot_cols$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols$name, 
       fill = plot_cols$color)


plot(bs$y1987, main = "Belarus small 1987", breaks = c(0, 1:4), col = plot_cols)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = names(plot_cols)[1:4], fill = plot_cols[1:4])

plot(bs$y1987, main = "Belarus small 1987", breaks = c(0, plot_cols1$breaks), col = plot_cols1$color)
legend("bottomleft", cex = 0.6, inset = 0,
       legend = plot_cols1$name, 
       fill = plot_cols1$color)

# ---------------------- plot abandonment age ---------------------- #
plot(b_age_r$y2017, main = "Belarus Age of Abandonment 2017")
plot(b_age_r[[28:31]])



# -------------------------- animate --------------------------- #
# --------------
# https://www.rdocumentation.org/packages/raster/versions/3.1-5/topics/animate

animate(bt, pause = 0.5, zlim = c(1, 4), maxpixels=5000, n=1,
        breaks = c(0, plot_cols$breaks), col = plot_cols$color)

```

```{r global-site-map}
r
plot(r$shaanxi$y1987)

r_extent <- lapply(r, raster::extent)
plot(r_extent$belarus)

site_sf <- lapply(r, FUN = function(x) {
  x %>% 
    extent() %>% 
    as(., 'SpatialPolygons') %>%
    st_as_sf()
  }) %>% 
  bind_rows() %>% 
  mutate(site = site_df$site, 
         label = gsub("_", "", site_df$label),
         lab_desc = paste0("(", label, ") ", site_df$description),
         desc = site_df$description)




plot(site_sf)

# basemap
world <- ne_countries(scale = "small", returnclass = "sf") # can set returnclass to sf or sp.

# set crs for site_sf 
st_crs(site_sf) <- st_crs(world$geometry)

# -------------------------------------------------------------------- #
# save site_sf
st_write(site_sf, dsn = paste0(p_dat_derived, "site_sf.shp"), append = FALSE)

# load back in:
site_sf <- st_read(paste0(p_dat_derived, "site_sf.shp"))

# bind sf with df
left_join(site_sf, site_df, by = site)
site_sf$site[9] == site_df$site[9]

# -------------------------------------------------------------------- #
gg_globe <- ggplot() + 
  theme_classic() +
  geom_sf(data = world %>% filter(continent != "Antarctica"), fill = NA, color = "gray") +
  geom_sf(data = site_sf, mapping = aes(fill = desc)) + 
  labs(#subtitle = "Map projection: longlat", 
       x = NULL, y = NULL) +
  theme(legend.position = "bottom") + 
  geom_label_repel(data = site_sf,
                   aes(label = label, geometry = geometry),
                   stat = "sf_coordinates",
                   min.segment.length = 0.0, segment.alpha = 1,
                   point.padding = 0.2, box.padding = 0.2,
                   label.size = 0.3, color = "black")


gg_globe

proj_text <- "moll"
gg_globe1 <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  labs(subtitle = paste0("Map projection: ", proj_text))


proj_text <- "eck4"
gg_globe2 <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  labs(subtitle = paste0("Map projection: ", proj_text))

# use this one:
proj_text <- "eqearth"
gg_globe3 <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  labs(subtitle = paste0("Map projection: ", proj_text))

proj_text <- "natearth2"
gg_globe4 <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  labs(subtitle = paste0("Map projection: ", proj_text))


plot_grid(gg_globe, gg_globe1, gg_globe2, gg_globe3, gg_globe4)
warnings()
# -------------------------------------------------------------------- #
# save map
png(filename = paste0(p_output, "plots/site_locations_w_labels.png"), 
    width = 9, height = 6, units = "in", res = 400)
print(gg_globe4 + labs(subtitle = NULL))
dev.off()


# long labels:
gg_site_locations_long <-
  ggplot() + 
  theme_classic() +
  geom_sf(data = world %>% filter(continent != "Antarctica"), fill = NA, color = "gray") +
  geom_sf(data = site_sf, mapping = aes(fill = lab_desc)) + 
  labs(x = NULL, y = NULL, fill = "") +
  theme(legend.position = "bottom") + 
  geom_label_repel(data = site_sf,
                   aes(label = desc,  
                       # label = label, # use this for single letter code
                       geometry = geometry),
                   stat = "sf_coordinates",
                   min.segment.length = 0.0, segment.alpha = 1,
                   point.padding = 0.2, box.padding = 0.2,
                   label.padding = 0.2,
                   label.size = 0.2, color = "black", direction = "both") +
  # labs(subtitle = paste0("Map projection: ", "natearth2")) + 
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", "natearth2"))) + 
  guides(fill = guide_legend(nrow = 4, ncol = 3))


ggsave(plot = gg_site_locations_long, 
       filename = paste0(p_output, "plots/site_locations_w_labels_long.png"),
       width = 9, height = 5, units = "in", dpi = 400)

# just chinese sites
ggplot() + 
  # coord_sf(CRS = st_crs("+proj=eck4")) + 
  geom_sf(data = filter(world, name %in% c("China")), fill = NA, color = "gray") +
  geom_sf(data = site_sf %>% filter(site %in% c("shaanxi", "chongqing")), mapping = aes(fill = site)) + 
  geom_sf_label(data = site_sf, aes(label = site)) + 
  labs(subtitle = paste0("Map projection: ", proj_text)) +
    theme_classic() +
  theme(legend.position = "bottom")


```




```{r exploratory-stats}
# explore some stats:
s_length
b_length
s_length[, .N, by = length]
b_length[, .N, by = length]

```

```{r calc-mean-length}
# calculate mean length
# -------------------------------------------------------------------- #
# ----------------- use lapply() to calculate mean length ------------ #
# -------------------------------------------------------------------- #
s_max_length[, mean(max_length)]
s_max_length[max_length > 0, mean(max_length)]
s_length_distill


mean_length_df <- lapply(site_df$site, FUN = function(x){
  length <- fread(input = paste0(p_dat_derived, "lengths/", x, "_length", run_label, ".csv"))
  max_length <- fread(input = paste0(p_dat_derived, "lengths/", x, "_max_length", run_label, ".csv"), 
                      select = "max_length") # drop x and y, makes loading and calculating much faster

  df <- data.frame(site = x,
                   mean_length = length[, mean(length)], # mean of all lengths
                   mean_length_thr3 = length[length >= 3, mean(length)], # mean length, assuming abandonment threshold of 5
                   mean_length_thr5 = length[length >= 5, mean(length)], # mean length, assuming abandonment threshold of 5
                   mean_length_max = max_length[max_length > 0, mean(max_length)], # mean of all lengths
                   mean_length_max_thr3 = max_length[max_length >= 3, mean(max_length)], # mean length, assuming abandonment threshold of 5
                   mean_length_max_thr5 = max_length[max_length >= 5, mean(max_length)] # mean length, assuming abandonment threshold of 5
                   )
  
  df # return df
  }
  )

# bind rows
mean_length_df <- bind_rows(mean_length_df)

# save site_df
write_csv(mean_length_df, path = paste0(p_dat_derived, "mean_length_df", run_label, ".csv"))

# re load
mean_length_df <- read.csv(file = paste0(p_dat_derived, "mean_length_df.csv"))
mean_length_df <- read.csv(file = paste0(p_dat_derived, "mean_length_df", run_label, ".csv"))






# testing code, old:
# ------------------------------------------ #
# ----------------- mean length ------------ #
# ------------------------------------------ #
s_length[, site := "shaanxi"]
b_length[, site := "belarus"]

length_all <- rbindlist(list(s_length, b_length))
object_size(length_all)

dat_mean_length <- length_all[, .(mean_length = mean(length)), by = site]
dat2_mean_length <- length_all[length >= 5, .(mean_length_thr5 = mean(length)), by = site]
dat_mean_length <- merge(dat_mean_length, dat2_mean_length, by = "site", sort = FALSE)
dat_mean_length

# can also calculate the mean length from the distilled dat
sum((b_distill$length * b_distill$freq)) / sum(b_distill$freq)

# ------------------------------------ #
# ----------- mean max length -------- #
# ------------------------------------ #
# max length, mean, etc.
s_length
s_max_length[, site := "shaanxi"]
b_max_length[, site := "belarus"]

max_length_all <- rbindlist(list(s_max_length, b_max_length))
object_size(max_length_all)

dat_mean_length_max <- max_length_all[, .(mean_length = mean(max_length)), by = site]
dat2_mean_length_max <- max_length_all[max_length >= 5, .(mean_length_thr5 = mean(max_length)), by = site]
dat_mean_length_max <- merge(
  dat_mean_length_max, 
  dat2_mean_length_max, by = "site", sort = FALSE)

dat_mean_length_max
dat_mean_length

# save and reload
save(dat_mean_length, dat_mean_length_max, 
     file = paste0(p_output, "mean_lengths.rds"))

load(file = paste0(p_output, "mean_lengths.rds"), 
     verbose = TRUE)

dat_mean_length
dat_mean_length_max
```


```{r plot-mean-length}
# -------------------------------------------------------------------- #
# ----------------- plot mean length of time abandoned ---------------- #
# -------------------------------------------------------------------- #

mean_length_df <- read.csv(file = paste0(p_dat_derived, "mean_length_df.csv"))

# pivot, add columns specifying abn threshold, all vs. max, etc.
mean_length_df_pivot <- mean_length_df %>% 
  pivot_longer(cols = starts_with("mean"), names_to = "col_names", values_to = "mean_length") %>%
  mutate(length_type = ifelse(grepl("max", col_names), "max", "all"),
         abn_threshold = ifelse(grepl("thr5", col_names), "5", 
                                ifelse(grepl("thr3", col_names), "3",
                                       "1")))

# mean mean length
mean_mean_df <- mean_length_df_pivot %>% 
  group_by(abn_threshold, length_type) %>%
  summarise(count = n(),
            mean_mean = mean(mean_length, na.rm = TRUE))


gg_mean_length <- 
  ggplot(data = mean_length_df_pivot %>% filter(abn_threshold == "5"),
         mapping = aes(x = fct_reorder2(site, abn_threshold, desc(mean_length)),
                       y = mean_length, 
                       color = length_type)) + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 330, vjust = 1, hjust = 0),
        plot.caption = element_text(face = "italic")) +
  labs(title = "Mean length of abandonment",
       #caption = "Counting only recultivation of 2 or more continuous years",
       linetype = NULL,
       color = "Mean of:", 
       y = "Mean length of time abandoned (years)", 
       x = "Site") +
  geom_point(size = 2) + 
  geom_hline(data = mean_mean_df %>% filter(abn_threshold == "5"), 
             mapping = aes(yintercept = mean_mean, 
                           col = length_type, 
                           linetype = "Overall \nMean")) + 
  scale_linetype_manual(values = c("Overall \nMean" = "dashed")) + 
    scale_colour_discrete(labels = c(all = "All periods", 
                                     max = "Max. length \nper pixel")) +
    guides(color = guide_legend(order = 1))
    



# -------------------------------------------------------------------- #
# ----------------- save ---------------- #
# -------------------------------------------------------------------- #

png(filename = paste0(p_output, "plots/mean_lengths_b1.png"), 
    width = 6, height = 5, units = "in", res = 400)
print(gg_mean_length)
dev.off()




# ------------ multiple abandonment thresholds ------------ #
gg_mean_length_all <- 
  ggplot(data = mean_length_df_pivot,
         mapping = aes(x = fct_reorder(site, mean_length), y = mean_length, fill = fct_reorder(site, mean_length))) + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0),
        plot.caption = element_text(face = "italic")) +
  labs(title = "Mean length of abandonment",
       caption = "Counting only recultivation of 2 or more continuous years",
       linetype = NULL,
       fill = "Site", 
       y = "Mean length of time abandoned (years)", 
       x = "Site") +
  geom_col(width = 0.75) + 
  facet_grid(length_type ~ abn_threshold,
             labeller = labeller(length_type = c(all = "all lengths", #old = "new",
                                                 max = "max length per pixel"),
                                 abn_threshold = c("1" = "abn threshold = 1",
                                                   "3" = "abn threshold = 3",
                                                   "5" = "abn threshold = 5"))) +
  geom_hline(data = mean_mean_df, aes(yintercept = mean_mean, linetype = "mean"),
             show.legend = TRUE,
             # alternatively, just yintercept = 12
             #linetype = "dashed",
             color = "black", size = 0.75) + 
  scale_linetype_manual(values = c("mean" = "dotted")) + 
  guides(fill = guide_legend(override.aes = list(linetype = 0)))



# -------------------------------------------------------------------- #
# ----------------- save ---------------- #
# -------------------------------------------------------------------- #

png(filename = paste0(p_output, "plots/mean_lengths_all_grid_b1.png"), 
    width = 8.5, height = 5, units = "in", res = 400)
print(gg_mean_length_all)
dev.off()



```

```{r distill-length-data}
  
# -------------------------------------------------------------------- #
# ----------------- use lapply() to distill all sites ---------------- #
# -------------------------------------------------------------------- #
# now, using lapply to run for all sites
# 2. Distill the length data, for use in histograms
length_distill_df <- lapply(site_df$site, FUN = function(x){
  length <- fread(input = paste0(p_dat_derived, "lengths/", x, "_length_b1.csv"))
  max_length <- fread(input = paste0(p_dat_derived, "lengths/", x, "_max_length_b1.csv"),
                      select = "max_length") # drop x and y, makes loading and calculating much faster

  dt <- length[, .(freq = .N), by = length
               ][, ':='(site = x, length_type = "all")]
  dt_max <- max_length[, .(freq = .N), by = max_length
                       ][order(max_length), 
                         ][, ':='(site = x, length_type = "max")
                           ][, length := max_length
                             ][, max_length := NULL][]
  dt <- bind_rows(dt, dt_max) # return dt
  dt
  }
  )

# bind rows
length_distill_df <- bind_rows(length_distill_df) %>% as.data.frame()


length_distill_df

# save site_df
write_csv(length_distill_df, path = paste0(p_dat_derived, "length_distill_df.csv"))

# re load
length_distill_df <- read.csv(file = paste0(p_dat_derived, "length_distill_df.csv"))










# old:

# testing code # 

# to use with ggplot, first distill the data

# regular, no thresholds
b_length_distill <- b_length[, .(freq = .N), by = length]
b_length_distill[, site := "belarus"]
s_length_distill <- s_length[, .(freq = .N), by = length]
s_length_distill[, site := "shaanxi"]

length_distill <- rbind(b_length_distill, s_length_distill)

# blip1
b_length_blip1_distill <- b_length_blip1[, .(freq = .N), by = length]
b_length_blip1_distill[, site := "belarus"]
s_length_blip1_distill <- s_length_blip1[, .(freq = .N), by = length]
s_length_blip1_distill[, site := "shaanxi"]

length_blip1_distill <- rbind(b_length_blip1_distill, s_length_blip1_distill)

# max_length

b_max_length_distill <- b_max_length[, .(freq = .N), by = max_length]
b_max_length_distill[, site := "belarus"]
s_max_length_distill <- s_max_length[, .(freq = .N), by = max_length]
s_max_length_distill[order(max_length),]

s_max_length_distill[, site := "shaanxi"]
max_length_distill <- rbind(b_max_length_distill, s_max_length_distill)

t1 <- s_length_distill[, ':='(site = site, length_type = "all")]

t2 <- s_max_length_distill[order(max_length), 
                           ][, ':='(site = site, length_type = "max")
                             ][, length := max_length
                               ][, max_length := NULL][]
t1
t2
bind_rows(t1, t2)

```

```{r histograms}

length_distill_df <- read.csv(file = paste0(p_dat_derived, "length_distill_df.csv"))
length_distill_df

# -------------------------------------------------------------------- #
# ----------------- plot histograms ---------------- #
# -------------------------------------------------------------------- #

length_distill_df %>% head()


ggplot(data = filter(length_distill_df, site == site_df$site[9], length > 0)) + 
  theme_classic() + 
  labs(title = paste0(site_df$description[9], ": histogram of time abandoned"),
       caption = "Recultivation threshold >= 2 years",
       linetype = "") +
  xlab("Time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) +
  geom_col(mapping = aes(x = length, y = freq/(10^6)), fill = "gray50") +
  facet_grid(rows = vars(length_type), scales = "free",
             labeller = labeller(length_type = c(all = "all abn. periods", #old = "new",
                                                 max = "max. length per pixel"))) +
  geom_vline(data = filter(mean_length_df_pivot, 
                           site == site_df$site[9],
                           abn_threshold == 1), 
             aes(xintercept = mean_length, linetype = "mean"),
             show.legend = TRUE,
             color = "darkblue", size = 0.75) + 
  scale_linetype_manual(values = c("mean" = "dashed")) + 
  theme(legend.position = c(0.85, 0.95), plot.caption = element_text(face = "italic"))

# -------------------------------------------------------------------- #
# ----------------- function ---------------- #
# -------------------------------------------------------------------- #
for (i in 1:11) {
  gg_hist <- ggplot(data = filter(length_distill_df, site == site_df$site[i], length > 0)) + 
    theme_classic() +
    labs(title = paste0(site_df$description[i], ": histogram of time abandoned"),
         caption = "Recultivation threshold >= 2 years",
         linetype = "") +
    xlab("Time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) +
    geom_col(mapping = aes(x = length, y = freq/(10^6)), fill = "gray50") +
    facet_grid(rows = vars(length_type), scales = "free",
               labeller = labeller(length_type = c(all = "all abn. periods", #old = "new",
                                                   max = "max. length per pixel"))) +
    # geom_vline(xintercept = 5, linetype="dashed", color = "red", size = 0.75) +
    # geom_vline(xintercept = 20, linetype="dashed", color = "forest green", size = 0.75) +
    geom_vline(data = filter(mean_length_df_pivot,
                             site == site_df$site[i],
                             abn_threshold == 1), 
               aes(xintercept = mean_length, linetype = "mean"),
               show.legend = TRUE, color = "darkblue", size = 0.75) + 
    scale_linetype_manual(values = c("mean" = "dashed")) +
    theme(legend.position = c(0.85, 0.95), plot.caption = element_text(face = "italic"))
    
  
  # save
  png(filename = paste0(p_output, "plots/", "length_hist_b1", site_df$label[i], ".png"), 
      width = 7, height = 5, units = "in", res = 400)
  print(gg_hist)
  dev.off()
}




# -------------------------------------------------------------------- #
# both site histograms

gg_length_hist_all_b1 <- ggplot(data = length_distill_df %>%
                                  filter(site %in% c("belarus", "shaanxi"),
                                         length_type == "all")) + 
  labs(title = "Histogram of time abandoned across all individual periods of abandonment",
       subtitle = "Recultivation threshold >= 2 years") +
  xlab("Time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) +
  geom_col(mapping = aes(x = length, y = freq/(10^6)), fill = "gray50") +
  facet_grid(rows = vars(site), scales = "free") +
  geom_vline(xintercept = 5, linetype="dashed", 
             color = "red", size = 0.75) +
  # geom_vline(xintercept = dat_mean_length$mean_length, linetype="dashed", color = "pink", size = 0.75,
  #            show.legend = TRUE, le) +
  geom_vline(xintercept = 20, linetype="dashed", color = "forest green", size = 0.75) +
  theme_classic()



# max_length
gg_max_length_hist_all_b1 <- ggplot(data = length_distill_df %>%
                                  filter(site %in% c("belarus", "shaanxi"),
                                         length_type == "max",
                                         length > 0)) + 
  labs(title = "Histogram of maximum time abandoned per pixel",
       subtitle = "Recultivation threshold >= 2 years") +
  xlab("Maximum time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) + 
  geom_col(mapping = aes(x = length, y = freq/(10^6)), fill = "gray50") +
  facet_grid(rows = vars(site), scales = "free") +
  geom_vline(xintercept = 5, linetype="dashed", color = "red", size = 0.75) +
  geom_vline(xintercept = 20, linetype = "dashed", color = "forest green", size = 0.75) +
  theme_classic()

gg_length_hist_all_b1
gg_max_length_hist_all_b1

# save to file ---------------- #
# all lengths
png(filename = paste0(p_output, "plots/length_hist_all_b1.png"), 
    width = 7, height = 5, units = "in", res = 400)
print(gg_length_hist_all_b1)
dev.off()

# max lengths
png(filename = paste0(p_output, "plots/max_length_hist_b1.png"), 
    width = 7, height = 5, units = "in", res = 400)
print(gg_max_length_hist_all_b1)
dev.off()









# old histograms
# beware... because of the way the bins are determined, the default histogram automatically lumps 1 and 2 together. better to first distill the data and use ggplot 
hist(s_length[[1]], main = "Histogram of Length of Time Abandoned \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")

hist(b_length[[1]])

hist(length_all[site == "shaanxi", length], main = "Histogram of Abandonment Period Lengths \n Shaanxi/Shanxi Provinces, China", xlab = "Time (years)")

hist(length_all[site == "belarus", length], main = "Histogram of Abandonment Period Lengths \n Belarus/Russia", xlab = "Time (years)")

hist(b_length[[1]], main = "Histogram of Abandonment Period Lengths \n Belarus/Russia", xlab = "Time (years)")
toc()

hist(b_length[[1]], main = "right = TRUE")
hist(b_length[[1]], right = FALSE, main = "right = FALSE")


# just belarus
ggplot(data = b_distill) + 
  geom_col(mapping = aes(x = length, y = freq), fill = "black") +
  theme_classic()

ggplot(data = b_length, aes(length)) + 
  geom_histogram() +
  theme_classic() # took forever!! Beware...


```

```{r site-area}
# see 2_data_processing.Rmd 
site_df_w_size
site_df

gg_site_area




```


```{r lc-abn-area-over-time}
s_dt[, .N, by = .(y1987)] #
s_dt[, .N, by = .(y2017)] #

s_dt[, .N, by = .(y1987, y1988)] #
s_dt[, table(y1987)]

grep("x$|y$", names(s_dt), value = TRUE, invert = TRUE)

s_dt[, -c("x", "y")]
s_dt[, .N, by = c(paste0("y", 1987:2017))] #

s_dt[, .N, by = .(y1987)][order(get("y1987"))]
DT <- s_dt[, .N, by = .(y1987)][order(get("y1987"))] %>% 
  as_tibble()

DT
i <- "y1987"
rename(DT, "lc" = i, 
           eval(i) = "N")
# s_dt[, c("i", "freq") := NULL]


# ------------- calculate area raster ---------------- #
s_area <- raster::area(s$y2017) # area in km2
res(s_area)[1] * # resolution of the raster, in degrees (lat/long)
  100 * # ~100-110 km per degree 
  1000 # 1000 m/km = 26.95 m resolution

plot(s_area)

summary(getValues(s_area))
median(getValues(s_area)) # 0.0006972 km2. 
median(getValues(s_area)) * 100 / 1 # 100 ha/km2

# median pixel size is 697 m2, 0.0697 ha, or 0.000697 km2. 
median(getValues(s_area)) * # km2
  100 * # 100 ha per km2 
  10000 # m2 per ha

# the difference between minimum and maximum cell size, in m2
(max(getValues(s_area)) - 
    min(getValues(s_area))
  ) * # in km2
  1000^2 # m2 / km 2


# abandoned area over time
s_age_r
plot(s_age_r$y2017)
plot(s_age_r$y2017 > 0)
cellStats((s_age_r$y2017 > 0), "sum")

s_age[y2017 > 0, .N] # the total number of pixels with non-zero abandonment ages in the year 2017

s_age[, lapply(.SD, mean)] # mean age of abandonment over time.
s_age[y1988 > 0, .N] # count of "abandoned" cells in a particular year
s_age[get("y2017") > 0, .N]
s_age[y2017 > 0, .N]


# calculate areas for lc and abn manually
lc_area_s <- cc_total_area_per_lc(land_cover_dt = s_dt, area_raster = s_area)
abn_area_s <- cc_calc_abn_area(s_age, s_area)
area_s <- rbind(lc_area_s, abn_area_s)



# -------------------------------------------------------------- #
# -------------------------------------------------------------- #
# ------------- calculate total area per lc ---------------- #
area_s <- cc_calc_area_per_lc_abn(land_cover_dt = s_dt, 
                                  abn_age_dt = s_age, 
                                  land_cover_raster = s$y2017)

# ------------- plot ---------------- #
cc_save_plot_lc_abn_area(input_area_df = area_s, subtitle = "Shaanxi/Shanxi Provinces, China", 
                         outfile_label = "s",
                         width = 6, height = 4)

# manually
gg_lc_abn_area_s <- ggplot(data = area_s, aes(year, area_ha)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  labs(y = expression("Area  (10"^{6}*" ha)") , 
       x = "Year", 
       title = "Area by Land Cover, with Abandonment",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Land Cover") + 
  geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                          group = lc, color = lc),
            size = 1.2)

gg_lc_abn_area_s

# filter to include only subsets
gg_lc_abn_area_s %+% filter(area_s, lc == "Abandoned") + labs(title = "Abandoned Area")
gg_lc_abn_area_s %+% filter(area_s, lc != "Abandoned")

gg_lc_abn_area_s
gg_abn_area_s

gg_lc_abn_area_s2
gg_lc_abn_area_s




ggplot(data = area_b1_s, aes(year, area_ha)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  labs(y = expression("Area  (10"^{6}*" ha)") , 
       x = "Year", 
       title = "Area by Land Cover, with Abandonment",
       subtitle = "Shaanxi/Shanxi Provinces, China",
       color = "Land Cover") + 
  geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                          group = lc, color = lc),
            size = 1.2)

area_b1_s %>% filter(lc == "Non-veg.")


# area in non-veg
area_b1_s %>% 
  select(-count) %>%
  pivot_wider(id_cols = c(year, lc), 
              names_from = lc, 
              values_from = area_ha)
  
```


```{r abandonment-persistence}
# testing
s_age[get(paste0("y", 1987:2017)[2]) > 0]
s_age[y1988 > 0]


# ----------------------- see functions in _util_dt_filter_functions ------------------------------------
# manual
persistence_count_long <- cc_calc_persistence(abn_age_dt = s_age, land_cover_raster = s$y2017, 
                                              stat_proportion = FALSE,
                                              NA_first = FALSE)

persistence_count_long2 <- cc_calc_persistence(abn_age_dt = s_age, land_cover_raster = s$y2017, 
                                              stat_proportion = FALSE, include_wide = TRUE,
                                              NA_first = FALSE)

# as a list

persistence_list_s <- cc_calc_persistence_all(abn_age_dt = s_age, land_cover_raster = s$y2017)


# ----------------------------------- plot ------------------------------------------------- #

# plot the count of pixels abandoned (or age 1) in each year. This shows that over time, a greater amount of land is abandoned at once.
ggplot(data = filter(persistence_list_s$count, time_abn == 1)) + 
  theme_classic() + 
  geom_point(mapping = aes(x = year_abn, y = area_ha, color = year_abn))


# save as a plot
cc_save_plot_abn_persistence(input_list = persistence_list_s, subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s")






#persistence_list_s <- cc_calc_persistence_all(abn_age_dt = s_age, land_cover_raster = s$y2017)
load()


# average proportion of abandoned land remaining, across time abandoned

df_av <- persistence_list_b1_s$na_last %>%
  mutate(year_abn = as_factor(year_abn)) %>%
  group_by(time_abn) %>%
  summarise(count = n(),
            sd = sd(proportion, na.rm = TRUE), 
            se = sd/sqrt(count),
            proportion = mean(proportion), 
            year_abn = as_factor("mean"))
df_av


# as percentage
base <- ggplot(data = persistence_list_b1_s$na_first) + 
    theme_classic() + 
    geom_line(mapping = aes(x = age, y = proportion,
                            group = year_abn, color = year_abn), 
              size = 1.25
    ) + 
    labs(y = "Proportion remaining abandoned", 
         x = "Years since initial abandonment", 
         title = "Persistence of Abandoned Land",
         subtitle = NULL, #subtitle,
         color = "Year Abandoned") + 
    scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom") +
    # geom_hline(yintercept=0.5, linetype="dashed", 
    #          color = "red", size = 0.75) +
    theme(legend.text = element_text(angle = 320, vjust = 1, hjust = 0))

base + geom_line(data = df_av, mapping = aes(x = time_abn, y = proportion),
              size = 3)
base %+% test

# ----------------------------------- plot ------------------------------------------------- #
gg_half_life_s <- ggplot(data = persistence_list_b1_s$na_first) + 
  theme_classic() + 
  geom_hline(yintercept=0.5, linetype="dashed", 
             color = "red", size = 0.75) +
  geom_line(mapping = aes(x = age, y = proportion,
                           group = year_abn, color = year_abn), 
             size = 1) + 
  # geom_smooth(method = "lm", formula = y ~ poly(x, 2),
  #             mapping = aes(x = age, y = proportion),
  #             color = "dark blue", fill = "blue", size = 1.5) +
    
  geom_ribbon(data = df_av, aes(x = time_abn, ymin = proportion - 1.96*se, ymax=proportion + 1.96*se), 
              color = "gray", fill = "gray", alpha=0.5) + 
  geom_line(data = df_av, mapping = aes(x = time_abn, y = proportion),
              size = 2, color = "black") +

  labs(y = "Proportion remaining abandoned", 
         x = "Years since initial abandonment", 
         title = "Persistence of Abandoned Land",
         subtitle = NULL, #subtitle,
         color = "Year Abandoned") + 
  scale_color_distiller(palette = "Greens") + 
  theme(legend.position = "bottom",
        legend.text = element_text(angle = 320, vjust = 1, hjust = 0))

gg_half_life_s
df_av %>% filter(proportion <= 0.51)



# save
png(filename = paste0(p_output, "plots/half_life_s.png"), 
    width = 7, height = 5, units = "in", res = 400)
print(gg_half_life_s)
dev.off()


# ------------------- additional models ------------------------------------------------- #
# y ~ log(x)
ggplot(data = persistence_list_b1_s$na_first) + 
    theme_classic() + 
    geom_point(mapping = aes(x = age, y = proportion,
                            group = year_abn, color = year_abn), 
              size = 1.25) + 
    labs(y = "Proportion remaining abandoned", 
         x = "Years since initial abandonment", 
         title = "Persistence of Abandoned Land",
         subtitle = NULL, #subtitle,
         color = "Year Abandoned") + 
    scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom") +
    theme(legend.text = element_text(angle = 320, vjust = 1, hjust = 0)) + 
  geom_smooth(method = "lm", formula = y ~ log(x),
              mapping = aes(x = age, y = proportion),
              color = "dark blue", fill = "blue", size = 1.5) + 
  geom_hline(yintercept=0.5, linetype="dashed", 
             color = "red", size = 0.75) + 
  geom_vline(xintercept = 24.16574)


# log(y) ~ x:
ggplot(data = persistence_list_b1_s$na_first) + 
    theme_classic() + 
  # note, needs to be log transformed
    geom_point(mapping = aes(x = age, y = log(proportion),
                            group = year_abn, color = year_abn), 
              size = 1.25) + 
    labs(y = "Proportion remaining abandoned", 
         x = "Years since initial abandonment", 
         title = "Persistence of Abandoned Land",
         subtitle = NULL, #subtitle,
         color = "Year Abandoned") + 
    scale_color_distiller(palette = "Greens") + theme(legend.position = "bottom") +
    theme(legend.text = element_text(angle = 320, vjust = 1, hjust = 0)) + 
  
  # log(y) ~ x
  geom_smooth(method = "lm", formula = log(y) ~ x,
              mapping = aes(x = age, y = proportion),
              color = "dark blue", fill = "blue", size = 1.5) + 
  geom_hline(yintercept=log(0.5), linetype="dashed", 
             color = "red", size = 0.75) + 
  geom_vline(xintercept = 23.1708)

```


```{r abn-gain-loss-area}
# calculate the abandonment area turnover
abn_area_change_s <- cc_calc_abn_area_diff(abn_age_dt = s_age, area_raster = s_area)

cc_save_plot_area_gain_loss(input_area_change_df = abn_area_change_s, 
                            subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s",
                            width = 6)


```

```{r abn-area-by-age-class}
area_s %>% filter(lc == "Abandoned")
persistence_list_s$count_na_first
persistence_list_s$count

# first plot
age_class0 <- ggplot(data = persistence_list_s$count_na_first) + 
  theme_classic() +
  geom_col(mapping = aes(x = year, y = area_ha / 10^3, group = year_abn, fill = year_abn)) + 
  labs(y = expression("Area abandoned (10"^{3}*" ha)") , 
         x = "Years since initial abandonment", 
         title = "Area of Abandoned Land, by Age Class",
         subtitle = "Shaanxi/Shanxi Province, China",
         fill = "Year Abandoned") + 
  scale_fill_distiller(palette = "Greens") + theme(legend.position = "bottom") + 
  scale_x_continuous(n.breaks = 10)

# trying some massaging
age_class_df <- persistence_list_s$count_na_first %>% 
  mutate(age = year - year_abn + 1) %>% 
  mutate(bins = ifelse(age > 0 & age <= 5, "1 to 5 years",
                       ifelse(age > 5 & age <= 10, "5 to 10 years",
                              ifelse(age > 10 & age <= 15, "10 to 15 years",
                                     ifelse(age > 15 & age <= 20, "15 to 20 years",
                                            ifelse(age > 20 & age <= 30, "20 to 30 years", NA)
                                            ))))) %>%
  mutate(bins = as_factor(bins))

# plot



# Function
cc_save_plot_area_by_age_class(input_list = persistence_list_s, 
                               subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s")

```






```{r save-rasters}
cc_save_map_pnv_hab_lc_abn(maxpixels = 3000000)

cc_save_map_lc_age_rasters(maxpixels = 3000000)

```


```{r animations}
site_index <- 1

tic()
cc_save_gif(raster = age_r[[site_index]], 
            npixels = 500000, 
            titles = paste0("Abandonment Age, ", 
                            capwords(site_df$site[site_index]), " ", 1987:2017),
            frames_per_second = 5,
            file_out = paste0(p_plots, "/", run_label, "/", "animation_abn_age",
                              site_df$label[site_index], ".gif"))
toc()




# ----------------------------------------------- #
# use animation::saveGIF() to save raster::animate()

file_out <- paste0(p_plots, "/", run_label, "/", "animation_land_cover",
                              site_df$label[site_index], ".gif")

saveGIF(animate(site_r[[site_index]], main = paste0("Land Cover, ", 
                            capwords(site_df$site[site_index]), " ", 1987:2017), 
                maxpixels = 500000, n = 1,
                breaks = c(0, plot_cols1$breaks), col = plot_cols1$color), 
          movie.name = file_out)

gif <- image_animate(image_read(file_out), fps = 5)
image_write(gif, file_out)


dev.off()
plot(site_r$shaanxi$y1987, main = "Shaanxi 1987", breaks = c(0, plot_cols1$breaks), col = plot_cols1$color, maxpixels = 10000)
legend("bottomleft", cex = 2, inset = 0,
       legend = plot_cols1$name, 
       fill = plot_cols1$color)  

```





```{r master-functions}
# Shaanxi master functions
# 1. ------------- calculate total area per lc, with abandonment ---------------- #
area_s <- cc_calc_area_per_lc_abn(land_cover_dt = s_dt, 
                                  abn_age_dt = s_age, 
                                  land_cover_raster = s$y2017)

cc_save_plot_lc_abn_area(input_area_df = area_s, subtitle = "Shaanxi/Shanxi Provinces, China", 
                         outfile_label = "s",
                         width = 5, height = 4)

# 2. ------------------------ abandonment persistence --------------------------- #
persistence_list_s <- cc_calc_persistence_all(abn_age_dt = s_age, land_cover_raster = s$y2017)

cc_save_plot_abn_persistence(input_list = persistence_list_s, subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s")


# 3. -------------------- calculate the abandonment area turnover ------------------- #
abn_area_change_s <- cc_calc_abn_area_diff(abn_age_dt = s_age, area_raster = s_area)

cc_save_plot_area_gain_loss(input_area_change_df = abn_area_change_s, 
                            subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s",
                            width = 6)

# 4. -------------------- plot abandonment area by age class ------------------- #
cc_save_plot_area_by_age_class(input_list = persistence_list_s, 
                               subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s")




# mega function to save all four plot types
tic()
cc_save_area_persistence_plots(land_cover_dt = s_dt, 
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017,
  subtitle = "Shaanxi/Shanxi Provinces, China",
  outfile_label = "_s"
  )
toc()

load(file = paste0(p_output, "abn_dat_products_s.rds"), verbose = TRUE)

# how do i deal with different thresholds of abandonment?

```


```{r belarus-plots}
# Belarus:

tic()
cc_save_area_persistence_plots(land_cover_dt = b_dt, 
  abn_age_dt = b_age, 
  land_cover_raster = b$y2017,
  subtitle = "Eastern Belarus/Smolensk, Russia",
  outfile_label = "_b"
  )
toc()

# generate plots
cc_save_area_persistence_plots(subtitle = "Shaanxi/Shanxi Provinces, China", outfile_label = "_s")

cc_save_area_persistence_plots(subtitle = "Shaanxi/Shanxi Provinces, China", input_site_label = "_s", 
                     outfile_label = "_s_all")

cc_save_area_persistence_plots(subtitle = "Eastern Belarus/Smolensk, Russia", input_site_label = "_b", 
                     outfile_label = "_b_all")



```

# Update to implement 5 year threshold
```{r n_lc_area}
# three files:
area_s
persistence_list_s
abn_area_change_s

# first, area

ggplot(data = area_s) +
    theme_classic() +
    # theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
    labs(y = expression("Area  (10"^{6}*" ha)") , 
         x = "Year", 
         title = "Area by Land Cover, with Abandonment",
         subtitle = subtitle,
         color = "Land Cover") + 
    geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                            group = lc, color = lc),
              size = 1.2) + 
    scale_x_continuous(n.breaks = 10)

abandonment_threshold <- 5

abandoned_area_df <- tibble(
    year = 1987:2017,
    lc = "Abandoned",
    count = sapply(1:31, function(i) {s_age[get(paste0("y", 1987:2017)[i]) >= abandonment_threshold, .N]}),
    count_all = sapply(1:31, function(i) {s_age[get(paste0("y", 1987:2017)[i]) > 0, .N]}),

    area_ha = count * median_cell_area_km2 * 100,
    area_all_ha = count_all * median_cell_area_km2 * 100
  )

s_age[y1992 >= 5, .N]

abandoned_area_df %>% print(n = 31)
filter(area, lc != "Abandoned")
n_area_s1 <- bind_rows(filter(area_s, lc != "Abandoned"), abandoned_area_df) %>% print(n = 155)

tic()
n_area_s <- cc_calc_area_per_lc_abn(land_cover_dt = s_dt,
                                    abn_age_dt = s_age, 
                                    land_cover_raster = s$y2017,
                                    abandonment_threshold = 5)
toc()
identical(n_area_s, n_area_s1)

# new updated plot
ggplot(data = n_area_s 
       %>% filter(lc != "Abandoned (all)") %>% 
         mutate(lc = recode(lc, "Abandoned (>5)" = "Abandoned"))
       ) +
  theme_classic() +
  # theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
  labs(y = expression("Area  (10"^{6}*" ha)") , 
       x = "Year", 
       title = "Area by Land Cover, with Abandonment",
       subtitle = subtitle,
       color = "Land Cover") + 
  geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                          group = lc, color = lc),
            size = 1.2) + 
  scale_x_continuous(n.breaks = 10) #+
  # scale_color_discrete(name = "COVER", 
  #                      labels = c("Abandoned (>5)",
  #                                 "Abandoned (all)", 
  #                                 "Crop", "Grassland", 
  #                                 "Non-veg", "Woody veg"))

n_area_s %>% select(lc) %>% unique() %>% arrange(lc)

persistence_list_s
abn_area_change_s

```

```{r n_persistence}
persistence_list_s

s_age
s

persistence_list_s <- cc_calc_persistence_all(
  abn_age_dt = s_age, land_cover_raster = s$y2017)

# starting with i + 1 (i.e. 1988), count the number of cells that are of i age, then the next year, with age 2, then the next year with age 3, etc.
# the j represents each cohort of abandonment. I think I can just start with the fifth year for the counts.
stat_proportion <- FALSE
NA_first <- TRUE
pl1 <- persistence_list
pl2 <- persistence_list

pl1
pl2


names(persistence_list) <- paste0("y", 1988:2017)
pl2[[1]][-c(1:4)]
abandonment_threshold
c(abandonment_threshold:31) %>% length
pl2[[1]][c(abandonment_threshold:31)]
pl_na1 <- persistence_list
pl_na2 <- persistence_list

pl_na1[[1]]
pl_na2[[1]]
test1 <- pl_na1[[30]]
test2 <- pl_na2[[30]]
test2[c(1:4)] <- NA

n_pl_na1 <- persistence_list
n_pl_na2 <- persistence_list

temp_vector[c(1:31)]
pl_na1
n_pl_na1

pl_na2
n_pl_na2
for(i in 1:30) {print(length(persistence_list[[i]]))}

temp_vector[c()]

# remove cells that are below threshold
if (NA_first){
  temp_vector[c((1:(abandonment_threshold - 1)) + j)] <- NA
} else {
  temp_vector[c(1:(abandonment_threshold - 1))] <- NA
}

persistence_long %>% arrange(year_abn, time_abn)
pl2[-c(1:4)]

 temp_vector4 <- c(
      if (NA_first) {rep(NA, j)
        } else {rep(NA, 0)},
      sapply(1:(31 - j), function(i) {
        abn_age_dt[get(paste0("y", 1987:2017)[i + j]) == i, .N]
      }),
      if (NA_first) {rep(NA, 0)
      } else {rep(NA, j)}
    )
 
temp_vector %>% length
temp_vector1 %>% length
temp_vector2 %>% length
temp_vector3 %>% length
temp_vector4
abandonment_threshold:(31 - 27)
sapply(abandonment_threshold:(31 - 27), function(i) {
        abn_age_dt[get(paste0("y", 1987:2017)[i + 27]) == i, .N]
      })

abn_age_dt[get(paste0("y", 1987:2017)[i + j]) == i, .N]
abn_age_dt[get(paste0("y", 1987:2017)[i + j]) == i, .N]
abn_age_dt[y1994 == 7, ]

count_s <- cc_calc_persistence(abn_age_dt = s_age, 
                               land_cover_raster = s$y2017, 
                               stat_proportion = FALSE,
                               NA_first = FALSE, include_wide = FALSE)



proportion <- cc_calc_persistence(abn_age_dt, land_cover_raster, 
                                  stat_proportion = TRUE,
                                  NA_first = FALSE, include_wide = FALSE)

count_na_first <- cc_calc_persistence(abn_age_dt, land_cover_raster, 
                                      stat_proportion = FALSE,
                                      NA_first = TRUE, include_wide = FALSE)

proportion_na_first <- cc_calc_persistence(abn_age_dt, land_cover_raster, 
                                           stat_proportion = TRUE,
                                           NA_first = TRUE, include_wide = FALSE)




# try the new functions

n_persistence_list_s <- cc_calc_persistence_all(
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017, 
  include_wide = FALSE,
  abandonment_threshold = 5,
  include_all_abandonment = FALSE
)
n_persistence_list_s$na_last %>% select(proportion) %>% summary()
n_persistence_list_s$na_first %>% select(proportion) %>% summary()

n_persistence_list_s1 <- cc_calc_persistence_all(
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017, 
  include_wide = FALSE,
  abandonment_threshold = 1
)

n_persistence_list_s_all <- cc_calc_persistence_all(
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017, 
  include_wide = FALSE,
  abandonment_threshold = 5,
  include_all_abandonment = TRUE
)

n_persistence_list_s_wide <- cc_calc_persistence_all(
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017, 
  include_wide = TRUE,
  abandonment_threshold = 5,
  include_all_abandonment = TRUE
)

pl_test <- 
  cc_calc_persistence(
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017, 
  stat_proportion = TRUE, # doesn't work for true
  NA_first = TRUE, # works for false, and for true?
  include_wide = FALSE,
  abandonment_threshold = 5
)
j <- 27
# doesn't work for 
stat_proportion = TRUE
NA_first = FALSE
include_wide = FALSE

stat_proportion = TRUE
NA_first = FALSE
include_wide = FALSE
abandonment_threshold = 1
# doesn't work for the na_first

# for NA_first = FALSE, it works
# for NA_first = TRUE, it works
persistence_list[[30]]
if(sum(persistence_list[[30]], na.rm = TRUE) == 0) {print("yes")}

test <- persistence_list[[30]]/max(persistence_list[[30]], na.rm = TRUE)

temp_vector[c(1:(31 - (abandonment_threshold - 1)))]

temp_vector[c()]

temp_vector[c(abandonment_threshold + 1:27)]
# try plotting:
cc_save_plot_abn_persistence
cc_save_plot_area_by_age_class
```

```{r n_age-class}

persistence_list_s


ggplot(data = filter(persistence_list_s$count_na_first, age >= 5)) + 
  theme_classic() +
  labs(y = expression("Area abandoned (10"^{3}*" ha)") , 
       x = "Year", 
       title = "Area of Abandoned Land, by Age Class",
       subtitle = subtitle,
       fill = "Age") + 
  #scale_x_continuous(n.breaks = 10) + 
  geom_col(mapping = aes(x = year, y = area_ha / 10^3, group = bins, fill = bins),
             position = position_stack(reverse = TRUE)
    ) +
  scale_fill_brewer(palette = "Greens", direction = 1) + 
  geom_line(data = filter(n_area_s, lc == "Abandoned (>5)"), mapping = aes(x = year, y = area_ha / (10^3)))
  


age_class_continuous <- age_class_base +
    geom_col(mapping = aes(x = year, y = area_ha / 10^3, group = age, fill = age),
             position = position_stack(reverse = TRUE)
    ) + 
    scale_fill_distiller(palette = "Greens", direction = 1)


  
  age_class_bins <- age_class_base +
    geom_col(mapping = aes(x = year, y = area_ha / 10^3, group = bins, fill = bins),
             position = position_stack(reverse = TRUE)
    ) +
    scale_fill_brewer(palette = "Greens", direction = 1) 
```


```{r n_abn_area_change}
abn_area_change_s

identical(s_age, abn_age_dt)
abn_age_dt

 # new. remove cells that are below threshold
    
abn_turnover_list
abn_turnover_list[[1]] %>% length()
abn_turnover_list[[1]]
i <- 1
j <- 3

# testing grounds:
temp_vector_diff <- c(
      rep(0, j),
      sapply(1:(31 - j), function(i) {
        abn_age_dt[get(paste0("y", 1987:2017)[i + j]) == i, .N]
      })
    )
# need to remove cells below abandonment threshold
temp_vector_diff[c(j + 1:(abandonment_threshold - 1))] <- 0

# trim to right length
if(length(temp_vector_diff) > 31){
  temp_vector_diff <- temp_vector_diff[c(1:31)]
  }

# calculate diff
temp_vector_diff <- diff(temp_vector_diff)

test <- cc_calc_abn_area_diff(abn_age_dt = s_age, 
                              land_cover_raster = s$y2017,
                              abandonment_threshold = 5)
cc_save_plot_area_gain_loss(
  input_area_change_df = test, 
  subtitle = "subtitle", 
  outfile_label = "test")
  

temp_vector_diff %>% length
abn_turnover_list[[30]] %>% length

abn_age_dt[get(paste0("y", 1987:2017)[i+1]) == i, .N]
abn_age_dt[get(paste0("y", 1987:2017)[i + j]) == i, .N]

    if (abandonment_threshold > 1) {
      if (NA_first){
        temp_vector[c((1:(abandonment_threshold - 1)) + j)] <- NA
      } else {
        temp_vector[c(1:(abandonment_threshold - 1))] <- NA
      }
      
      if(length(temp_vector) > 31){
        temp_vector <- temp_vector[c(1:31)]
      }
    }
```


```{r run-full-functions}

# ------------------------------------------ #
# ----------------- Shaanxi ---------------- #
# ------------------------------------------ #
tic()
cc_summarize_abn_dts(
  land_cover_dt = s_dt, 
  abn_age_dt = s_age, 
  land_cover_raster = s$y2017,
  outfile_label = "_s",
  abandonment_threshold = 5,
  include_all = TRUE
  )
toc()

# load(file = paste0(p_output, "abn_dat_products_s.rds"), verbose = TRUE) # now happens inside the function


tic()
cc_save_area_persistence_plots(
  input_path = p_output, 
  output_path = paste0(p_output, "test/"),
  site_label = "_s", 
  blip_label = "_blip1",
  outfile_label = "_s_blip1",
  subtitle = "Shaanxi/Shanxi Provinces, China (recult. >= 2)", 
  subtitle_all = "Shaanxi/Shanxi Provinces, China, all abandonment (recult. >= 2)",
  save_all = TRUE
)
toc()


# ------------------------------------------ #
# ----------------- Belarus ---------------- #
# ------------------------------------------ #
tic()
cc_summarize_abn_dts(
  land_cover_dt = b_dt, 
  abn_age_dt = b_age, 
  land_cover_raster = b$y2017,
  outfile_label = "_b",
  abandonment_threshold = 5,
  include_all = TRUE
  )
toc()


load(file = paste0(p_output, "abn_dat_products_b.rds"), verbose = TRUE)

# 
tic()
cc_save_area_persistence_plots(
  input_site_label = "_b", 
  blip_label = "_blip1",
  outfile_label = "_b_blip1",
  subtitle = "Eastern Belarus/Smolensk, Russia (recult. >= 2)", 
  subtitle_all = "Eastern Belarus/Smolensk, Russia, all abandonment (recult. >= 2)", 
  save_all = TRUE
)
toc()


# ------------------------------------------ #
# ------------ Fragmentation --------------- #
# ------------------------------------------ #
cc_save_frag_plots(input = frag_dat, outfile_label = NULL)


```

```{r save-plots-loop}

# see data.frame of all sites
site_df


i <- 2
site_df$description[i]

for (i in 1:11) {
  blip_label <- "_b1"

  cc_save_area_persistence_plots(
    input_path = p_output, 
    output_path = paste0(p_output, "plots_loop/"),
    site_label = site_df$label[i], 
    blip_label = blip_label,
    outfile_label = paste0(blip_label, site_df$label[i]),
    subtitle = paste0(site_df$description[i], ", (recult. >= 2)"), 
    subtitle_all = paste0(site_df$description[i], ", all abandonment (recult. >= 2)"),
    save_all = FALSE
  )
}



for (i in c(1, 9)) {
  blip_label <- "_blip1"
  cc_save_area_persistence_plots(
    input_path = p_output, 
    output_path = paste0(p_output, "plots_loop1/"),
    site_label = site_df$label[i], 
    blip_label = blip_label,
    outfile_label = paste0(blip_label, site_df$label[i]),
    subtitle = paste0(site_df$description[i], ", (recult. >= 2)"), 
    subtitle_all = paste0(site_df$description[i], ", all abandonment (recult. >= 2)"),
    save_all = FALSE
  )
}

site_df$description

```


```{r abandonment-rate}
# two ways to calculate this:

# 
# 1. Amount of additional land abandoned in that year (the net gain in abandoned land) / the total amount of agricultural land at the start of the time series
# 2. Amount of additional land abandoned in that year (the net gain in abandoned land) / the amount of agricultural land in the time step immediately preceding that year
blip_label <- "_b1"
site_label <- site_df$label[9]
load(file = paste0(p_output, "abn_dat_products", blip_label, site_label, ".rds"), verbose = TRUE)


# area in agriculture, at the start of the time series
area_b1_s %>% filter(year == "1987", lc == "Cropland") %>% select(area_ha) %>% unlist(use.names = F)

# area in agriculture, in the immediately preceding year
rate_year <- 1992 # starting with 1992

area_b1_s %>% filter(year == c(rate_year - 1), lc == "Cropland") %>% select(area_ha) %>% unlist(use.names = F)


# area abandoned, net
abn_area_change_b1_s %>% filter(year == rate_year, direction == "net") %>% select(area_ha) %>% unlist(use.names = F)

# area abandoned, gross
abn_area_change_b1_s %>% filter(year == rate_year, direction == "gain") %>% select(area_ha) %>% unlist(use.names = F)


# make a data.frame - development
site_df


df1 <- abn_area_change_b1_s %>% 
  filter(direction == "net") %>% 
  mutate(area_abn_yr = area_ha) %>%
  select(year, area_abn_yr)

abn_area_change_b1_s %>% 
  filter(direction == "net") %>% 
  select(year, area_abn_yr = area_ha)

filter(area_b1_s, year == "1987", lc == "Cropland")$area_ha
filter(area_b1_s, lc == "Cropland")$area_ha[1:30]

abn_area_change_b1_s

# develop method to calculate the right data.frame
# abn_rate_df <- abn_area_change_b1_s %>% 
#   filter(direction == "net") %>% 
#   select(year, area_abn_yr = area_ha) %>% 
#   mutate(site = site_df$site[9],
#          cropland_start = filter(area_b1_s, year == "1987", lc == "Cropland")$area_ha,
#          cropland_yr_before = filter(area_b1_s, lc == "Cropland")$area_ha[1:30],
#          abn_rate_start = area_abn_yr/cropland_start,
#          abn_rate = area_abn_yr/cropland_yr_before)


# ------------------------------------------------------------------------------------ #
# write for loop to create rate_df and bind rows
# ------------------------------------------------------------------------------------ #

abn_rate_l <- vector(mode = "list", length = length(site_df$site))
names(abn_rate_l) <- site_df$site

for (i in 2:11) {
  load(file = paste0(p_output, "abn_dat_products", blip_label, site_df$label[i], ".rds"), verbose = TRUE)

  abn_rate_l[[i]] <- eval(parse(text = paste0("abn_area_change_b1", site_df$label[i]))) %>% 
  filter(direction == "net") %>% 
  select(year, area_abn_yr = area_ha) %>% 
  mutate(site = site_df$site[i],
         cropland_start = filter(eval(parse(text = paste0("area_b1", site_df$label[i]))), year == "1987", lc == "Cropland")$area_ha,
         cropland_yr_before = filter(eval(parse(text = paste0("area_b1", site_df$label[i]))), lc == "Cropland")$area_ha[1:30],
         abn_rate_start = area_abn_yr/cropland_start,
         abn_rate = area_abn_yr/cropland_yr_before)
}


# Add Belarus
load(file = paste0(p_output, "abn_dat_products", "_blip1", site_df$label[1], ".rds"), verbose = TRUE)

abn_rate_l[[1]] <- eval(parse(text = paste0("abn_area_change_blip1", site_df$label[1]))) %>% 
  filter(direction == "net") %>% 
  select(year, area_abn_yr = area_ha) %>% 
  mutate(site = site_df$site[1],
         cropland_start = filter(eval(parse(text = paste0("area_blip1", site_df$label[1]))), year == "1987", lc == "Cropland")$area_ha,
         cropland_yr_before = filter(eval(parse(text = paste0("area_blip1", site_df$label[1]))), lc == "Cropland")$area_ha[1:30],
         abn_rate_start = area_abn_yr/cropland_start,
         abn_rate = area_abn_yr/cropland_yr_before)

# condense list into a data.frame
abn_rate_df <- bind_rows(abn_rate_l)

# save the new data.frame
write.csv(abn_rate_df, file = paste0(p_dat_derived, "abn_rate_df.csv"))

# ------------------------------------------------------------------------------------ #
# plot results
# ------------------------------------------------------------------------------------ #

ggplot(data = filter(abn_rate_df, site == "shaanxi")) + 
  theme_classic() +
  geom_point(mapping = aes(x = year, y = abn_rate_start*100), col = "red") + 
  geom_point(mapping = aes(x = year, y = abn_rate*100), col = "blue") + 
  labs(title = "Abandonment Rate", subtitle = , x = "Year", y = "Abandonment Rate (%)" )


# make groups
abn_rate_df <- abn_rate_df %>% mutate(cluster = ifelse(site %in% site_df$site[1:3], "a",
                                        ifelse(site %in% site_df$site[4:6], "b",
                                               ifelse(site %in% site_df$site[7:9], "c", 
                                                      ifelse(site %in% site_df$site[10:11], "d", NA
                                        )))))


gg_abn_rate <- ggplot(data = abn_rate_df) + 
  theme_classic() +
  geom_line(mapping = aes(x = year, y = abn_rate*100, group = site, color = site), #position = position_dodge(0.5), 
            size = 1.25) + 
  labs(title = "Abandonment Rate", subtitle = "Percent of cropland in prior year abandoned the following year", x = "Year", y = "Abandonment Rate (%)") + 
  facet_wrap(vars(cluster)) + theme(strip.background = element_blank(), strip.text = element_blank())

gg_abn_rate_start <- ggplot(data = abn_rate_df) + 
  theme_classic() +
  geom_line(mapping = aes(x = year, y = abn_rate_start*100, group = site, color = site), #position = position_dodge(0.5), 
            size = 1.25) + 
  labs(title = "Abandonment Rate", subtitle = "Percent of total cropland in 1987 abandoned each year", x = "Year", y = "Abandonment Rate (%)") + 
  facet_wrap(vars(cluster)) + theme(strip.background = element_blank(), strip.text = element_blank())


gg_abn_rate
gg_abn_rate_start

# save png
png(filename = paste0(p_output, "plots/abn_rate.png"), 
    width = 8.5, height = 5, units = "in", res = 400)
print(gg_abn_rate)
dev.off()


# save png
png(filename = paste0(p_output, "plots/abn_rate_start.png"), 
    width = 8.5, height = 5, units = "in", res = 400)
print(gg_abn_rate_start)
dev.off()


persistence_list_b1_s

# Rate, method 1


```




```{r clean-up}

env_size(ls())
object_size(hl)

```


# explore latest run 3-5-21

```{r load-cluster-results}
run_file_paths <- list.files(path = paste0(p_dat_derived, run_label)) %>% 
  grep("pers", ., value = TRUE)

persistence_df <- read.csv(file = paste0(p_dat_derived, run_label, "/", run_file_paths[i]))

run_dfs <- lapply(run_file_paths, function(i) {
  read.csv(file = paste0(p_dat_derived, run_label, "/", i))
})

names(run_dfs) <- site_df$site
run_dfs <- run_dfs %>% bind_rows(.id = "site") %>% as_tibble()


# when is the first year abandonment can take place?
run_dfs %>% filter(area_ha > 0) %>% group_by(site) %>% summarize(first_year = min(year_abn))

```


```{r save-figs}
# run plots loop:

if(!dir.exists(paste0(p_output, "plots/", run_label))) {
  dir.create(paste0(p_output, "plots/", run_label))
}

lapply(1:11, function(i) {
  cc_save_area_persistence_plots(
    input_path = paste0(p_dat_derived, run_label), 
    output_path = paste0(p_output, "plots/", run_label, "/"),
    site_label = site_df$label[i], 
    run_label = run_label,
    outfile_label = paste0(run_label, site_df$label[i]),
    site = site_df$site[i],
    subtitle = paste0(site_df$description[i]), # ", 5- and 8-year temp. filter"
    subtitle_all = paste0(site_df$description[i], ", all abandonment (no threshold)"),
    save_all = FALSE
  )
})
```

```{r loop-save-comp-panels}
lapply(1:11, function(i) {
  cc_4_panel_plots(
    input_path = paste0(p_dat_derived, run_label), 
    output_path = paste0(p_output, "plots/", run_label, "/"),
    outfile_label = paste0(run_label, site_df$label[i]),
    site = site_df$site[i]
  )
})


# Shaanxi main text panel

cc_4_panel_plots(
    input_path = paste0(p_dat_derived, run_label), 
    output_path = paste0(p_output, "plots/", run_label, "/"),
    outfile_label = paste0(run_label, site_df$label[9]),
    site = site_df$site[9],
    main_text_panel = TRUE
  )


```


# Presentation Figures:

```{r lc-abn-by-age}
input_path <- paste0(p_dat_derived, run_label)
output_path <- paste0(p_output, "plots/", run_label, "/presentation/")
outfile_label <- paste0(run_label, site_df$label[9])
site <- site_df$site[9]
col_palette <- plot_cols


cc_presentation_summary_plots <- function(input_path, 
                             output_path,
                             outfile_label = paste0(run_label, site_label),
                             site,
                             width = 9, height = 11,
                             col_palette = plot_cols,
                             subtitle = NULL,
                             site_desc) {
  
  area_df <- read_csv(file = paste0(input_path, "/", site, "_result_area",  run_label, ".csv"))
  persistence_df <- read.csv(file = paste0(input_path, "/", site, "_result_persistence",  run_label, ".csv"))
  turnover_df <- read.csv(file = paste0(input_path, "/", site, "_result_turnover",  run_label, ".csv"))
  length_distill_df <- read.csv(file = paste0(input_path, "/", "length_distill_df", run_label, ".csv"))
  mean_length_df <- read.csv(file = paste0(input_path, "/", "mean_length_df", run_label, ".csv"))
  # site <- "shaanxi"
  input_site <- site
  
  # ------------- calculate total area per lc, with abandonment ---------------- #
  gg_lc_abn_area <-
    ggplot(data  = area_df #%>% filter(lc != "Abandoned (>1)")
    ) +
    theme_classic() +
    # theme(axis.text.x = element_text(angle = 320, vjust = 1, hjust = 0)) +
    labs(y = expression("Area  (10"^{6}*" ha)") , 
         x = "Year", 
         #title = "Area by Land Cover, with Abandonment",
         #subtitle = subtitle,
         color = NULL #"Land Cover"
         ) + 
    geom_line(mapping = aes(x = year, y = area_ha / (10^6), # convert to millions of ha
                            group = lc, color = fct_reorder(lc, lc, .desc = TRUE)),
              size = 1.5) + 
    theme(legend.position = "bottom",
          legend.title = element_text(size = 10)) +
    guides(color = guide_legend(nrow = 2, ncol = 3)) +
    
    scale_color_manual(values = col_palette)
  # scale_color_brewer(palette = "Greens")
  # scale_color_viridis(discrete = TRUE)
  
  
  # ------------------------ abandonment persistence --------------------------- #
  gg_persistence <-
    ggplot(data = persistence_df) + 
    theme_classic() + 
    labs(#title = "Persistence of Abandoned Land",
      #subtitle = subtitle,
      color = "Year \nAbandoned \n(Cohort)") + 
    scale_color_distiller(palette = "Greens") +
    theme(legend.position = c(0.9, 0.7),
      #legend.direction = "horizontal"
      #legend.position = "bottom", legend.text = element_text(angle = 330, vjust = 1, hjust = 0)
      legend.title = element_text(size = 10)
    ) +
    geom_line(mapping = aes(x = age, y = proportion,
                            group = year_abn, color = year_abn), 
              size = 1.25) + 
    labs(y = "Proportion remaining abandoned", 
         x = "Years since initial abandonment")
  
  
  # -------------------- calculate the abandonment area turnover ------------------- #
  gg_turnover <-
    ggplot() +
    theme_classic() + 
    labs(y = expression("Annual area turnover (10"^{3}*" ha)"), 
         x = "Year", 
         #title = "Change in Area of Abandoned Land",
         #subtitle = subtitle,
         fill = NULL, #"Annual Change",
         color = NULL) + 
    scale_color_manual(values = c("black"),
                       labels = "Net Change") + 
    scale_fill_manual(values = brewer_pal(palette = "Greens")(5)[3:2],
                      labels = c("Area Gained", "Area Lost")) + 
    theme(legend.position = "bottom",
      #legend.position = c(0.2, 0.7),
      # legend.direction = "horizontal",
      legend.title = element_text(size = 10)
    ) +
    geom_col(data = filter(turnover_df, change != "net"),
             mapping = aes(x = year, y = area_ha / (10^3), 
                           group = change, fill = change)) + 
    geom_line(data = filter(turnover_df, change == "net"),
              mapping = aes(x = year, y = area_ha / (10^3), color = "Net Change in Area"),
              size = 1.5)
  
  
  # -------------------- plot abandonment area by age class ------------------- #
  gg_age_class_bins <-
    ggplot(data = persistence_df) + 
    theme_classic() +
    labs(y = expression("Area abandoned (10"^{3}*" ha)") , 
         x = "Year", 
         #title = "Area of Abandoned Land, by Age Class",
         #subtitle = subtitle,
         fill = "Age \n(years)") +
    geom_col(mapping = aes(x = year, y = area_ha / 10^3, 
                           fill = fct_reorder(bins, age)),
             position = position_stack(reverse = FALSE)) +
    theme(
      #legend.position = c(0.1, 0.8),
      #legend.position = "bottom",
      legend.title = element_text(size = 10)
      ) +
    scale_fill_brewer(palette = "Greens", direction = 1)
  
  
  # histogram:
  gg_hist <-
    ggplot(data = filter(length_distill_df, site == input_site,# site_df$site[i], 
                         length > 0)) + 
    theme_classic() +
    labs(color = "Mean") +
    xlab("Time abandoned (years)") + ylab(expression("Count  (10"^{6}*" pixels)")) +
    geom_col(mapping = aes(x = length, y = freq/(10^6)), fill = "gray70") +
    facet_grid(rows = vars(length_type), scales = "free",
               labeller = labeller(length_type = c(all = "all abn. periods", #old = "new",
                                                   max = "max. length \nper pixel"))) +
    # means
    geom_vline(data = filter(mean_length_df, site == input_site, #site_df$site[i], 
                             abn_threshold != 3), 
               mapping = aes(xintercept = mean_length, color = as_factor(abn_threshold)#, linetype = "mean (>1)"
                             ),
               show.legend = TRUE, size = 1, linetype = "dashed"
               ) + 
    
    scale_color_manual(values = c("5" = "#C51B7D", "1" = "#F1B6DA"), 
                       labels = c("5" = "Mean (>=5)", "1" = "Mean (>1)")) +
    
    theme(#legend.position = c(0.85, 0.95)
          )
  
  title <- ggdraw() + 
              draw_label(
                site_desc,
                fontfamily = "Tahoma",
                x = 0, hjust = 0) +
              theme(# add margin on the left of the drawing canvas,
                # so title is aligned with left edge of first plot
                plot.margin = margin(0, 0, 0, 5))
  
  plot_combo1 <- plot_grid(gg_lc_abn_area + theme(legend.position = "top"), 
                     gg_age_class_bins + theme(legend.position = c(0.2, 0.7)),
                     ncol = 2, rel_widths = c(1, 1), align = "h", axis = "b")
  
  plot_combo2 <- plot_grid(gg_persistence, 
                     gg_turnover + theme(legend.position = "top"),
                     ncol = 2, rel_widths = c(1, 1), align = "h", axis = "b")
  
  # save fig 1:
  ggsave(filename = paste0(output_path, "summary_panel_1", outfile_label, ".png"),
         plot = plot_grid(title, plot_combo1,
                          ncol = 1, nrow = 2, rel_heights = c(0.2, 4)),
       width = 9, height = 4.5, units = "in", dpi = 400)
  
  # save fig 2:
  ggsave(filename = paste0(output_path, "summary_panel_2", outfile_label, ".png"),
         plot = plot_grid(title, plot_combo2,
                          ncol = 1, nrow = 2, rel_heights = c(0.2, 4)),
       width = 9, height = 4.5, units = "in", dpi = 400)
  
  
  # for main preso: shaanxi
  # ggsave(filename = paste0(output_path, "summary_panel_1", outfile_label, "_main_preso.png"),
  #        plot = plot_combo1,
  #      width = 9, height = 4.5, units = "in", dpi = 400)
  # 
  # ggsave(filename = paste0(output_path, "summary_panel_2", outfile_label, "_main_preso.png"),
  #        plot = plot_combo2,
  #      width = 9, height = 4.5, units = "in", dpi = 400)
  
}

lapply(1:11, function(i) {
  cc_presentation_summary_plots(
    input_path = paste0(p_dat_derived, run_label), 
    output_path = paste0(p_output, "plots/", run_label, "/presentation/"),
    outfile_label = paste0(run_label, site_df$label[i]),
    site = site_df$site[i],
    site_desc = site_df$description[i]
  )
})

```

```{r extrapolation-combo}
# see chunk 'extrapolation-panel' in 4_decay_models.Rmd
# just b and c, for presentation
ggsave(plot = 
         plot_grid(gg_extrapolation_panel_age_b + 
                     scale_x_continuous(breaks = seq(from = 2000, to = 2120, by = 40)) #+
                     # theme(legend.position = "bottom") + 
                     # guides(col = guide_legend(nrow = 4, ncol = 3))
                   , 
                     gg_extrapolation_panel_area_c + scale_x_continuous(breaks = seq(from = 2000, to = 2120, by = 40)) #+ theme(legend.position = "bottom")
                   ,
                     #rel_widths = c(1, 1.2),
                     # labels = c("b", "c"),
                   ncol = 2
                     ),
       filename = paste0(p_plots, run_label, "/presentation/", "extrapolation_combo", run_label, ".png"),
       width = 9, height = 3.5, units = "in", dpi = 400
)
```

```{r mean-trend}
# see "4_decay_models.Rmd"
png(filename = paste0(p_plots, run_label, "/presentation/", "model_decay_curves_by_site_l3_wide", run_label, ".png"), 
    width = 7, height = 4, units = "in", res = 400)
print(gg_model_curves_by_site_l3 + 
        # labs(caption = NULL) +
        scale_x_continuous(n.breaks = 15) + 
        theme(legend.position = c(0.9, 0.65)))
dev.off()


# gg_extrapolation_panel_trend_a <-
  ggplot(data = fitted_df_l3 %>% 
           left_join(max_age_extrapolation, by = "site") %>% 
           filter(age < 140),
       mapping = aes(x = age, y = fitted, color = fct_reorder(site, max_age))) +
  theme_classic() +
  geom_line(size = 1.1) +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "gray70") + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(#title = "Decay of abandoned land over time", 
       #caption = "lm formula: (proportion - 1) ~ 0 + log(time + 1):cohort + (time):cohort",
       x = "Time since initial abandonment (years)", 
       y = "Proportion of abandoned land remaining",
       color = "Site") + 
  guides(col = guide_legend(reverse = TRUE)) + 
  scale_x_continuous(breaks = seq(from = 0, to = 140, by = 20))

  
  
```

```{r abn-area-by-age-bin-grid}

dat_l

# plot
gg_age_class_bins_grid <-
    ggplot(data = dat_l) + 
    theme_classic() +
    labs(y = expression("Area abandoned (10"^{3}*" ha)") , 
         x = "Year", 
         #title = "Area of Abandoned Land, by Age Class",
         #subtitle = subtitle,
         fill = "Age (years)") +
    geom_col(mapping = aes(x = year, y = area_ha / 10^3, 
                           fill = fct_reorder(bins, age)),
             position = position_stack(reverse = FALSE)) +
    theme(
      #legend.position = c(0.1, 0.8),
      #legend.position = "bottom",
      legend.title = element_text(size = 10)
      ) +
    scale_fill_brewer(palette = "Greens", direction = 1) +
      facet_wrap(vars(site), scales = "free_y", labeller = as_labeller(cap_labels)) +  # see _util_misc_functions.R
    theme(legend.position = c(0.885, 0.12), 
        legend.spacing = unit(2, units = "mm"), 
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0)) + 
      guides(fill = guide_legend(nrow = 3, ncol = 2))




# save
ggsave(plot = gg_age_class_bins_grid,
       filename = paste0(p_plots, run_label, #"/presentation", 
       "/abn_area_by_age_grid", run_label, ".pdf"),

       width = 7, height = 5, units = "in", dpi = 400
)

```

```{r turnover-grid}
turnover_dat <- read_csv(file = paste0(p_dat_derived, "turnover_dat", run_label, ".csv"))

# ---------------------------------------------------------------------- #
# plot facet grid
# ---------------------------------------------------------------------- #

gg_turnover_facet_grid <-
  ggplot() +
    theme_classic() + 
    labs(y = expression("Annual area turnover (10"^{3}*" ha)"), 
         x = "Year", 
         #title = "Change in Area of Abandoned Land",
         #subtitle = subtitle,
         fill = NULL, #"Annual Change",
         color = NULL) + 
    scale_color_manual(values = c("black"),
                       labels = "Net Change") + 
    scale_fill_manual(values = brewer_pal(palette = "Greens")(5)[3:2],
                      labels = c("Area Gained", "Area Lost")) + 
    geom_col(data = filter(turnover_dat, change != "net"),
             mapping = aes(x = year, y = area_ha / (10^3), 
                           group = change, fill = change)) + 
    geom_line(data = filter(turnover_dat, change == "net"),
              mapping = aes(x = year, y = area_ha / (10^3), color = "Net Change in Area"),
              size = 1) + 
  facet_wrap(vars(site),
             labeller = as_labeller(cap_labels),
             scales = "free") +
    theme(legend.position = c(0.9, 0.12),
          legend.title = element_text(size = 10))
  
gg_turnover_facet_grid


ggsave(plot = gg_turnover_facet_grid,
       filename = paste0(p_plots, run_label, "/turnover_grid", run_label, ".pdf"), 
    width = 7, height = 5, units = "in"
)
```


```{r abn-age-maps-2017}
# load in the data.tables
library(data.table)
list.files()
age_dt_files <- s
lapply(age_dt_files, function(i) {fread(i, select = c("Year","Jan","Feb","Mar","Apr","May","Jun"))})

age_r[[1]][["y2017"]]

plot(age_r[[1]][["y2017"]], maxpixels = 50000)



age_2017_grid <- 
  plot_grid(plot(age_r[[1]][["y2017"]], main = site_df$site[1]),
          plot(age_r[[2]][["y2017"]], main = site_df$site[2]),
          plot(age_r[[3]][["y2017"]], main = site_df$site[3]),
          plot(age_r[[4]][["y2017"]], main = site_df$site[4]),
          nrow = 2, ncol = 2, labels = "auto")

ggsave(plot = age_2017_grid,
       file = paste0(p_plots, run_label, "/abn_age_2017_maps.pdf"),
       width = 9, height = 5, units = "in", dpi = 400)

test_dt
ggplot() +
 geom_raster(data = test_dt, 
             mapping = aes(x = x, y = y, fill = y2017)) + 
  theme_classic() +
  coord_quickmap()

par(mfrow = c(3, 4))
for (i in 1:11) {
  levelplot(age_r[[i]][["y2017"]], main = site_df$site[i])
}
  


# directly with raster:

age_r[[1]][["y2017"]]
age_2017_l <- lapply(1:11, function(i) {
  temp <- age_r[[i]][["y2017"]]
  temp <- raster::aggregate(temp, fact = 100)
  temp
})

names(age_2017_l) <- site_df$site
for (i in 1:11) {
  names(age_2017_l[[i]]) <- site_df$site[i]
  }

# set map color scheme
map_colors <- c("#F2F2F2", viridis(30, direction = 1))  # colorblindness-safe


# -------------------------------------------------------- #
# try one, with ggplot
# -------------------------------------------------------- #

# mp1 <- 
  gplot(age_2017_l[[1]]) + 
        geom_raster(aes(fill = value)) +
        # facet_wrap(~ variable, nrow = 1,
        #            #labeller = labeller(variable = new_labels_lookup)
        #            ) +
        scale_fill_gradientn(colors = map_colors, na.value = "white",
                             limits = c(0, 30)
                             ) + 
        labs(y = NULL, x = names(age_2017_l[[1]])) + 
        theme(rect = element_blank(), line = element_blank(), 
              axis.line = element_blank(), 
              axis.ticks = element_blank(), 
              axis.ticks.length = unit(0, "pt"), axis.text = element_blank(),
              legend.position = "right") + 
        coord_equal()
  
for (i in 1:11) {
  assign(x = paste0("mp_", i), 
         value = gplot(age_2017_l[[i]]) + 
           geom_raster(aes(fill = value)) +
           scale_fill_gradientn(colors = map_colors, 
                                na.value = "white", limits = c(0, 30)) +
           labs(y = NULL, x = names(age_2017_l[[i]])) + 
           theme(rect = element_blank(), line = element_blank(), 
                 axis.line = element_blank(), axis.ticks = element_blank(), 
                 axis.ticks.length = unit(0, "pt"), axis.text = element_blank(),
                 legend.position = "none") + 
           coord_fixed()
         )
  }


plot_grid(mp_1, mp_2, mp_3, mp_4, get_legend(mp_2 + theme(legend.position = "right")), nrow = 1, rel_widths = c(1.3, 1.2, 1, 1, 0.5))

# -------------------------------------------------------- #
# plot with base raster plots
# -------------------------------------------------------- #

plot(age_2017_l[[2]], 
     col = map_colors, 
     main = site_df$description[2],
     axes = F, legend = T, box = F)

ggsave()
pdf()
png(paste0(p_plots, run_label, "/abn_age_2017_maps_testrr.png"), 
    width = 7, height = 6, units = "in", res = 400
    )
par(mfrow=c(3, 4), mar=c(1,1,2,1), oma = c(1, 1, 1, 1))

for (i in 1:11) {
  # assign(
    # x = paste0("mp", i), 
    # value = 
      plot(age_2017_l[[i]], 
                 main = site_df$description[i],
                 col = map_colors,
                 axes = FALSE, legend = FALSE, box = FALSE)
  # )
}


# add standalone legend at the end
plot.new() # must add a new plot window
plot(age_2017_l[[1]], col = map_colors,
   legend.only = TRUE,
   legend.width = 2,
   legend.shrink = 1.4, cex = 5,
   smallplot=c(0.2, 0.35, 0.15, 0.85))#; par(mar = par("mar")) 
# small plot works as follows:
# smallplot=c(min % from left, max % from left, min % from bottom, max % from bottom).
dev.off()


library(gridExtra)
grid.arrange(mp1, mp2)
```


```{r aggregate-abn-age}
# aggregate using max function
age_2017_aggregated_10_max_l <- lapply(1:11, function(i) {
  temp <- age_r[[i]][["y2017"]]
  temp <- raster::aggregate(temp, fact = 10, fun = max)
  temp
})
# update names of the list items, and rename the raster layers after each site
names(age_2017_aggregated_10_max_l) <- site_df$site
for (i in 1:11) {
  names(age_2017_aggregated_10_max_l[[i]]) <- site_df$site[i]
}


# aggregate with mean, after removing short-term fallowing 
age_2017_aggregated_10_mean_l <- lapply(1:11, function(i) {
  temp <- age_r[[i]][["y2017"]]
  temp[temp < 5] <- NA # exclude short-term fallowing:
  temp <- raster::aggregate(temp, fact = 10, fun = mean, na.rm = TRUE)
  temp
})
# update names of the list items, and rename the raster layers after each site
names(age_2017_aggregated_10_mean_l) <- site_df$site
for (i in 1:11) {
  names(age_2017_aggregated_10_mean_l[[i]]) <- site_df$site[i]
}


# plot(age_2017_aggregated_10_max_l$mato_grosso)
# plot(age_r$mato_grosso$y2017)
plot(age_2017_aggregated_10_mean_l$mato_grosso)
plot(age_r$mato_grosso$y2017)

# set lattice levelplot settings
lattice.options(
  layout.heights=list(bottom.padding=list(x=0), top.padding=list(x = 0)),
  layout.widths=list(left.padding=list(x=0), right.padding=list(x=0))
  )

# create a color palette with the NA color (the plot panel background) set to gray
myTheme <- viridisTheme()
myTheme$panel.background$col <- 'gray95' 

# save level plots to objects
for (i in 1:11) {
  assign(
  x = paste0("lp_ag_mean", site_df$label[i]),
  value =
      levelplot(
        # age_2017_aggregated_10_max_l[[i]],
        age_2017_aggregated_10_mean_l[[i]],
        main = site_sf$lab_desc[i],
        colorkey = TRUE,
        scales=list(draw=TRUE),
        par.settings = myTheme,
        at = seq(5, 31, by = 1), 
        xlab = NULL, ylab = NULL,
        margin = FALSE
        )
  )
}


# map of site locations:
gg_site_locations <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  theme(legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, "cm"))

# create plot_grid elements
pan_top <- plot_grid(lp_ag_w, lp_ag_b, lp_ag_v, lp_ag_o, nrow = 1)
pan_l <- plot_grid(lp_ag_n, lp_ag_mg, ncol = 1)
pan_r <- plot_grid(lp_ag_s, lp_ag_c, ncol = 1)
pan_bottom <- plot_grid(lp_ag_g, lp_ag_bh, lp_ag_i, nrow = 1, ncol = 3)

# create plot_grid elements
pan_top <- plot_grid(lp_ag_mean_w, lp_ag_mean_b, lp_ag_mean_v, lp_ag_mean_o, nrow = 1)
pan_l <- plot_grid(lp_ag_mean_n, lp_ag_mean_mg, ncol = 1)
pan_r <- plot_grid(lp_ag_mean_s, lp_ag_mean_c, ncol = 1)
pan_bottom <- plot_grid(lp_ag_mean_g, lp_ag_mean_bh, lp_ag_mean_i, nrow = 1, ncol = 3)

pan_middle <- plot_grid(pan_l, gg_site_locations, pan_r, NULL,
          rel_widths = c(1, 2, 1, 0.05),
          nrow = 1, ncol = 4)

ggsave(plot = plot_grid(NULL, pan_top, pan_middle, pan_bottom, 
                        ncol = 1, nrow = 4,
                        rel_heights = c(0.05, 1, 1.8, 1)),
       filename = paste0(p_plots, run_label, #"/presentation", 
       "/site_locations_w_abn_age_ag_mean_10_gray", run_label, ".pdf"),

       width = 14, height = 10, units = "in", dpi = 400
       )


```


```{r comp-fig-site-abn-age-w-location}

myTheme <- viridisTheme()
myTheme$regions$col <- viridis(n = 100, direction = -1)
myTheme$panel.background$col = 'gray95' 

lattice.options(
  layout.heights=list(bottom.padding=list(x=0), top.padding=list(x = 0)),
  layout.widths=list(left.padding=list(x=0), right.padding=list(x=0))
  )

# for testing
for (i in 1:11) {
  assign(
  x = paste0("tp", i),
  value =
      levelplot(
        age_2017_l[[i]],
        # age_r[[i]][["y2017"]],
        main = site_sf$lab_desc[i],
        colorkey = TRUE, scales=list(draw=TRUE),
        par.settings = myTheme,
        # col.regions = map_colors,
        # col.regions = viridis(n = 31),
        at = seq(5, 31, by = 1), 
        xlab = NULL, ylab = NULL, margin = FALSE
        )
  )
}


# make levelplots for full rasters
for (i in 1:11) {
  assign(
  x = paste0("lp", site_df$label[i]),
  value =
      levelplot(
        age_r[[i]][["y2017"]],
        main = site_sf$lab_desc[i],
        colorkey = TRUE,
        scales=list(draw=TRUE),
        par.settings = myTheme, # use myTheme for gray background
        at = seq(5, 31, by = 1), 
        xlab = NULL, ylab = NULL,
        margin = FALSE
        )
  )
}

gg_site_locations <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  theme(legend.position = "none",
        plot.margin = margin(0, 0, 2, 0, "mm"))

# for testing:
# pan_top <- plot_grid(tp11, tp1, tp10, tp8, nrow = 1)
# pan_l <- plot_grid(tp7, tp6, ncol = 1)
# pan_r <- plot_grid(tp9, tp3, ncol = 1)
# pan_bottom <- plot_grid(tp4, tp2, tp5, nrow = 1, ncol = 3)

# with full rasters, gray background
pan_top <- plot_grid(lp_w, lp_b, lp_v, lp_o, nrow = 1)
pan_l <- plot_grid(lp_n, lp_mg, ncol = 1)
pan_r <- plot_grid(lp_s, lp_c, ncol = 1)
pan_bottom <- plot_grid(lp_g, lp_bh, lp_i, nrow = 1, ncol = 3)

pan_middle <- plot_grid(pan_l, gg_site_locations, pan_r, NULL,
          rel_widths = c(1, 2, 1, 0.05),
          nrow = 1, ncol = 4)

# save composite figure with map
ggsave(plot = plot_grid(NULL, pan_top, pan_middle, pan_bottom, 
                        ncol = 1, nrow = 4,
                        rel_heights = c(0.05, 1, 1.8, 1)),
       filename = paste0(p_plots, run_label, #"/presentation", 
       "/site_locations_w_abn_age_gray", run_label, ".pdf"),
       width = 14, height = 10, units = "in", dpi = 400
       )



# lp1:lp11 are with regular viridis theme, with white as the background
# lp_b : lp_w are with a gray background

# -------------------------------------------------------- #
# save plain composite figure ---------------------------- #
# 

ggsave(plot = 
         # plot_grid(lp1, lp2, lp3, lp4, lp5, lp6, lp7, lp8, lp9, lp10, lp11, NULL, nrow = 3, ncol = 4),
         plot_grid(lp_b, lp_bh, lp_c, lp_g, lp_i, lp_mg, lp_n, lp_o, lp_s, lp_v, lp_w, NULL, nrow = 3, ncol = 4),
       filename = paste0(p_plots, run_label, #"/presentation", 
       # "/abn_age_maps", 
       "/abn_age_maps_2017_rev", 
       run_label, ".pdf"),
       width = 14, height = 10, units = "in", dpi = 400
       )

ggsave(plot = 
         plot_grid(gg_site_locations #+ labs(title = "Site locations")
                   ,
                   plot_grid(lp_b, lp_bh, lp_c, 
                             lp_g, lp_i, lp_mg, 
                             lp_n, lp_o, lp_s, 
                             lp_v, lp_w, NULL, 
                             nrow = 4, ncol = 3),
                   rel_heights = c(1.5, 4),
                   nrow = 2, ncol = 1
                   ),
       filename = paste0(p_plots, run_label, #"/presentation", 
       "/abn_age_maps_test2", 
       run_label, ".pdf"),
       width = 11, height = 13, units = "in", dpi = 400
       )
```

```{r map-max-age-composite}

myTheme <- viridisTheme()
myTheme$regions$col <- viridis(n = 100, direction = -1)
myTheme$panel.background$col = 'gray95' 

lattice.options(
  layout.heights=list(bottom.padding=list(x=0), top.padding=list(x = 0)),
  layout.widths=list(left.padding=list(x=0), right.padding=list(x=0))
  )


# make levelplots for full rasters
for (i in 1:11) {
  assign(
  x = paste0("lp_max", site_df$label[i]),
  value =
      levelplot(
        max_age_r[[i]],
        main = site_df$description[i],
        colorkey = TRUE,
        scales=list(draw=TRUE),
        par.settings = myTheme, # use myTheme for gray background
        at = seq(5, 31, by = 1), 
        xlab = NULL, ylab = NULL,
        margin = FALSE
        )
  )
}

gg_site_locations <- gg_globe +
  coord_sf(expand = TRUE, crs = st_crs(paste0("+proj=", proj_text))) +
  theme(legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, "cm"))

# for testing:
# pan_top <- plot_grid(tp11, tp1, tp10, tp8, nrow = 1)
# pan_l <- plot_grid(tp7, tp6, ncol = 1)
# pan_r <- plot_grid(tp9, tp3, ncol = 1)
# pan_bottom <- plot_grid(tp4, tp2, tp5, nrow = 1, ncol = 3)

# with full rasters, gray background
pan_max_top <- plot_grid(lp_max_w, lp_max_b, lp_max_v, lp_max_o, nrow = 1)
pan_max_l <- plot_grid(lp_max_n, lp_max_mg, ncol = 1)
pan_max_r <- plot_grid(lp_max_s, lp_max_c, ncol = 1)
pan_max_bottom <- plot_grid(lp_max_g, lp_max_bh, lp_max_i, nrow = 1, ncol = 3)

pan_max_middle <- plot_grid(pan_max_l, gg_site_locations, pan_max_r, NULL,
          rel_widths = c(1, 2, 1, 0.05),
          nrow = 1, ncol = 4)

# save plain composite figure ---------------------------- #
# 

ggsave(plot = 
         plot_grid(lp_max_b, lp_max_bh, lp_max_c, lp_max_g, 
                   lp_max_i, lp_max_mg, lp_max_n, lp_max_o, 
                   lp_max_s, lp_max_v, lp_max_w, NULL, nrow = 3, ncol = 4),
       filename = paste0(p_plots, run_label,
       "/abn_age_maps_max_rev", 
       run_label, ".pdf"),
       width = 14, height = 10, units = "in", dpi = 400
       )
```


```{r end}
env_size(ls())

```


