---
title: "Timing and persistence of abandoned agricultural land (outline)"
author: "Christopher Crawford, 1/31/2021, Princeton University"
output: 
  bookdown::word_document2:
      reference_docx: /Users/christophercrawford/Google_Drive/_Projects/writing/scripts/word_style_ref.docx
      number_sections: false
bibliography: /Users/christophercrawford/Google_Drive/Library/library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction

Populations are in flux around the world, as people seek new economic opportunities in cities and flee changing environments and conflicts.
Coupled with environmental changes and other factors that render some agricultural lands economically inviable, this rural outmigration has contributed to a growing global trend of agricultural abandonment.
In a world with increasing competition for land, abandoned agricultural lands are highly sought after for diverse goals such as increased cultivation, biofuel production, and carbon-sequestration; to conservation scientists, this land represents a potentially large source of new habitat for wildlife as vegetation regenerates.

However, understanding agricultural abandonment and its potential impacts on biodiversity requires not only detailed information on where and how abandonment is taking place, but critically, what happens to abandoned lands after they are abandoned.
Recent advances in satellite imagery-based mapping have made it possible to produce maps of agricultural abandonment with both high spatial resolution and temporal resolution (which prior studies lack), allowing us to ask questions about the timing and trajectories of agricultural abandonment [@Yin2020].
Here, we utilize a new 31 year time-series of agricultural abandonment derived from publicly available Landsat imagery (1987-2017) to investigate how long abandonment lasts, how abandoned lands "decay," and which factors seem to determine the length of abandonment and recultivation.

## Research questions

Our primary goal is to understand the temporal nature of agricultural abandonment by exploring the trajectories taken by each piece of abandoned land through time.
Our main point is simple: abandoned land is not a permanent phenomenon.
In fact, the period of abandonment varies quite a bit around the world and through time.

We address three specific questions:

1. How long is land actually abandoned for, on average, and how does abandonment length vary through space (i.e. at different sites)?
2. How quickly is land recultivated, as measured through "abandonment decay rates"?
    a. How do these decay rates vary through time at each site, and how do they vary across sites? (What proportion of abandoned land remains abandoned long-term [e.g. >20 years])
3. What factors best predict abandonment trajectories?
    a. What predicts which pieces of land are abandoned for the longest periods of time? In other words, are some areas more likely to experience more durable abandonment?
    b. What predicts recultivation? Are less suitable lands recultivated more quickly? Are more recently abandoned lands more frequently recultivated? In other words, does the probability that a piece of abandoned land will be recultivated depend on how long it has been abandoned for?

Together, these questions provide a clearer picture of the timing and persistence of agricultural abandonment, improving our understanding the conservation implications of agricultural abandonment, and providing crucial context to inform policies designed to manage abandoned lands. 

# Methods

- Defining abandonment (cropland that remains uncultivated for five or more consecutive years)
- Describe abandonment map data from Yin et al. 2020.
- Data processing & filtering steps, including a) removing non-abandonment pixels, b) passing a temporal filter to remove instances of recultivation that last only 1 year, and c) tracking abandonment trajectories through time
- Modeling abandonment decay: motivation (see next paragraph), modeling approach, and diagnostic steps.
- Spatial predictors: modeling approach and which factors are investigated (e.g. ag suitability, climate/precipitation, topography, and population)

Investigating decay rates provides a more nuanced understanding of how long abandonment lasts than the simple mean abandonment length.
The mean abandonment length tells us about the general persistence of abandoned land at a given site over the course of the full time series. 
It tells us, on average, how long land has been abandoned for *so far*.
This value is limited by when the majority of the abandonment took place at a site, because we cannot directly observe how long abandonment extends beyond the end of the time series.
Will a piece of land abandoned in 2011 last for two additional years past 2017, or 20?

To address this challenge, we look at groups ("cohorts") of pixels that are abandoned in a particular year and track their trajectories through time.
For each cohort of abandoned land, we track recultivation, or "abandonment decay," by measuring the proportion of each cohort that remains abandoned through time, relative to when that land was first abandoned.
Decay rates provide information about how long to expect a piece of land to remain abandoned and how this varies through time. 

# Results

Note: the figures listed below are individual plots. Multiple plots can be combined into composite figures, with multiple panels.

Fig. 0. Site locations  

### 1. Mean abandonment lengths, by site [the basics]

Fig. 1. Mean abandonment length (years) by site, for all periods and max length  
Fig. 2. Area abandoned, by age class (single site, illustratively)  
Fig. 3. Area by land cover, over time (single site - possibly moved to SI)  

### 2. Decay rates, a) by site (average), and b) rate of change of decay rates, by site

Fig. 4. Decay trajectories (showing individual trajectories for a single site, illustratively)  
Fig. 5. Mean decay rate coefficients by site (vertical with two panels, showing log and linear terms for each site)  
Fig. 6. Mean decay trajectory, by site over 50 years.  
Fig. 7. Decay rate rate of change (vertical, one coefficient for each site, e.g. based on the *time to 50%*; individual site trends over time will be in the SI)  

### 3. Spatial predictors of age and recultivation

Fig. 8. Coefficients on spatial predictors (vertical, showing coefficients on slope, elevation, suitability, population)  
Fig. 9. Maps of a) abandonment *age in 2017* and b) *max age* for example site.  

# References
